mat::MpiVectorTool Class Reference
#include <mat_mpi_tool.hpp>
Public Member Functions
MpiVectorTool ()
int beg ()
int end ()
void Barrier ()
void Init (MPI_Comm comm_world, std::vector< int > start, std::vector< int > end)
void Init (MPI_Comm &comm_world, int vec_size)
bool Empty ()
void Allocate (std::vector< double > &x)
double AllreduceSum (double &x)
int AllreduceSum (int &x)
double InnerProduct (const std::vector< double > &a, const std::vector< double > &b)
double L2Norm (const std::vector< double > &a)
void init (std::vector< double > &a, const double val)
void init (std::vector< double > &a, const std::vector< double > &b)
void zero (std::vector< double > &a)
Detailed Description
Definition at line 12 of file mat_mpi_tool.hpp.
Constructor & Destructor Documentation
MpiVectorTool()
mat::MpiVectorTool::MpiVectorTool () [inline]
Definition at line 14 of file mat_mpi_tool.hpp.
                 {
    empty_ = true;
  }
Member Function Documentation
Allocate()
void mat::MpiVectorTool::Allocate (std::vector< double > & x) [inline]
Definition at line 58 of file mat_mpi_tool.hpp.
                                      {
    for (size_t i = 0; i < size_; ++i) {
      MPI_Bcast((void *)&x[table_beg_[i]], table_len_[i], MPI_DOUBLE, i, comm_world_);
    }
    MPI_Barrier(comm_world_);
  }
Referenced by mat::CsrMat< T >::MultiplyMpi(), mat::EllMat< T >::MultiplyMpi(), and solver::BicgstabMpi< matrixT >::solve().
AllreduceSum() [1/2]
double mat::MpiVectorTool::AllreduceSum (double & x) [inline]
Definition at line 65 of file mat_mpi_tool.hpp.
                                 {
    double temp_g = x;
    MPI_Allreduce(&x, &temp_g, 1, MPI_DOUBLE, MPI_SUM, comm_world_);
    return temp_g;
  }
Referenced by InnerProduct().
AllreduceSum() [2/2]
int mat::MpiVectorTool::AllreduceSum (int & x) [inline]
Definition at line 71 of file mat_mpi_tool.hpp.
                           {
    int temp_g = x;
    MPI_Allreduce(&x, &temp_g, 1, MPI_INT, MPI_SUM, comm_world_);
    return temp_g;
  }
Barrier()
void mat::MpiVectorTool::Barrier () [inline]
Definition at line 19 of file mat_mpi_tool.hpp.
{ MPI_Barrier(comm_world_); }
beg()
int mat::MpiVectorTool::beg () [inline]
Definition at line 17 of file mat_mpi_tool.hpp.
{ return beg_; }
Referenced by mat::CsrMat< T >::MultiplyMpi(), mat::EllMat< T >::MultiplyMpi(), and solver::BicgstabMpi< matrixT >::solve().
Empty()
bool mat::MpiVectorTool::Empty () [inline]
Definition at line 57 of file mat_mpi_tool.hpp.
{ return empty_;}
end()
int mat::MpiVectorTool::end () [inline]
Definition at line 18 of file mat_mpi_tool.hpp.
{ return end_; }
Referenced by Init(), Init(), mat::CsrMat< T >::MultiplyMpi(), mat::EllMat< T >::MultiplyMpi(), and solver::BicgstabMpi< matrixT >::solve().
Init() [1/2]
void mat::MpiVectorTool::Init (MPI_Comm & comm_world, int vec_size) [inline]
Definition at line 31 of file mat_mpi_tool.hpp.
                                                {
    size_ = mpi::GetSize(comm_world);
    std::vector<int> len(size_);
    std::vector<int> start(size_);
    std::vector<int> end(size_);
    std::cout << "size_" << size_;
    for (int i = 0; i < size_; i++) {
      len[i] = vec_size / size_;
    }
    for (int i = 0; i < vec_size % size_; i++) {
        len[i]++;
    }
    start[0] = 0;
    for (int i = 1; i < size_; i++) {
        start[i] = start[i - 1] + len[i - 1];
    }
    for (int i = 0; i < size_; i++) {
        end[i] = start[i] + len[i];
    }
    Init(comm_world, start, end);
  }
References end(), mpi::GetSize(), and Init().
Init() [2/2]
void mat::MpiVectorTool::Init (MPI_Comm comm_world, std::vector< int > start, std::vector< int > end) [inline]
Definition at line 21 of file mat_mpi_tool.hpp.
                                {
    empty_ = false;
    comm_world_ = comm_world;
    rank_ = mpi::GetRank(comm_world_);
    size_ = mpi::GetSize(comm_world_);
    InitLocal(start, end);
    InitGlobal(start, end);
  }
References end(), mpi::GetRank(), and mpi::GetSize().
Referenced by Init(), mat::SparseMat< T >::InitMpi(), and mat::SparseMat< T >::InitMpi().
init() [1/2]
void mat::MpiVectorTool::init (std::vector< double > & a, const double val) [inline]
Definition at line 92 of file mat_mpi_tool.hpp.
                                                           {
    auto A = a.data() + beg_;
#pragma omp parallel for simd default(none) firstprivate(A, val, len_) \
    schedule(static)
    for (size_t i = 0; i < len_; ++i) {
      *(A + i) = val;
    }
  }
Referenced by zero().
init() [2/2]
void mat::MpiVectorTool::init (std::vector< double > & a, const std::vector< double > & b) [inline]
Definition at line 101 of file mat_mpi_tool.hpp.
                                                                     {
    auto A = a.data() + beg_;
    auto B = b.data() + beg_;
#pragma omp parallel for simd default(none) firstprivate(A, len_, B) \
    schedule(static)
    for (size_t i = 0; i < len_; ++i) {
      *(A + i) = *(B + i);
    }
  }
InnerProduct()
double mat::MpiVectorTool::InnerProduct (const std::vector< double > & a, const std::vector< double > & b) [inline]
Definition at line 77 of file mat_mpi_tool.hpp.
                                                                                     {
    double temp_l{0.0};
    auto A = a.data() + beg_;
    auto B = b.data() + beg_;
#pragma omp parallel for simd reduction(+:temp_l) default(none) \
            firstprivate(A, B, len_) schedule(static)
    for (size_t i = 0; i < len_; ++i) {
      temp_l += *(A + i) * *(B + i);
    }
    return AllreduceSum(temp_l);
  }
References AllreduceSum().
Referenced by solver::LinearSolverMpi< MatType >::InnerProduct(), and L2Norm().
L2Norm()
double mat::MpiVectorTool::L2Norm (const std::vector< double > & a) [inline]
Definition at line 90 of file mat_mpi_tool.hpp.
{ return sqrt(InnerProduct(a, a)); }
References InnerProduct().
Referenced by solver::BicgstabRestartMpi< matrixT >::solve(), and solver::BicgstabMpi< matrixT >::solve().
zero()
void mat::MpiVectorTool::zero (std::vector< double > & a) [inline]
Definition at line 111 of file mat_mpi_tool.hpp.
{ init(a, 0.0); }
References init().
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/mat_mpi_tool.hpp