mat::CsrMat< T > Class Template Reference
#include <csr_sparse_mat.hpp>
Public Member Functions
CsrMat ()
CsrMat (int rows, int cols)
CsrMat (int n)
CsrMat (typename SparseMat< T >::CSR_type c)
void resize (int rows, int cols)
void resize (int n)
void Multiply (std::vector< T > &x, std::vector< T > &r) override
void MultiplyMpi (std::vector< T > &x, std::vector< T > &r)
void init (int Idx_len, int ptr_len)
void Set (const typename SparseMat< T >::CSR_type &csr)
void Show ()
SparseMat< T >::CSR_type GetCsr ()
Public Member Functions inherited from mat::SparseMat< T >
SparseMat (int rows, int cols)
SparseMat (int n)
SparseMat ()
void multiply_omp (std::vector< T > &x, std::vector< T > &r)
int row () const
int col () const
std::vector< T > Multiply (std::vector< T > &x)
std::vector< T > operator* (std::vector< T > &x)
void Construct (int rows, int cols)
void InitMpi (MPI_Comm comm_world, std::vector< int > beg, std::vector< int > end)
void InitMpi (MPI_Comm comm_world, int vec_size)
Additional Inherited Members
Public Types inherited from mat::SparseMat< T >
using CSR_type = std::tuple< std::vector< int >, std::vector< int >, std::vector< T > >
Public Attributes inherited from mat::SparseMat< T >
MpiVectorTool mpi_
Detailed Description
template<typename T>
class mat::CsrMat< T >
Definition at line 16 of file csr_sparse_mat.hpp.
Constructor & Destructor Documentation
CsrMat() [1/4]
template<typename T >
mat::CsrMat< T >::CsrMat () [inline]
Definition at line 18 of file csr_sparse_mat.hpp.
: SparseMat<T>() {}
CsrMat() [2/4]
template<typename T >
mat::CsrMat< T >::CsrMat (int rows, int cols) [inline]
Definition at line 20 of file csr_sparse_mat.hpp.
: SparseMat<T>(rows, cols) { SelfConstruct(); }
CsrMat() [3/4]
template<typename T >
mat::CsrMat< T >::CsrMat (int n) [inline]
Definition at line 22 of file csr_sparse_mat.hpp.
: SparseMat<T>(n) { SelfConstruct(); }
CsrMat() [4/4]
template<typename T >
mat::CsrMat< T >::CsrMat (typename SparseMat< T >::CSR_type c) [inline]
Definition at line 24 of file csr_sparse_mat.hpp.
{ Set(c); }
References mat::CsrMat< T >::Set().
Member Function Documentation
GetCsr()
template<typename T >
SparseMat< T >::CSR_type mat::CsrMat< T >::GetCsr () [inline]
Definition at line 96 of file csr_sparse_mat.hpp.
                                         {
    return make_tuple(ptr_, idx_, val_);
  }
init()
template<typename T >
void mat::CsrMat< T >::init (int Idx_len, int ptr_len) [inline]
Definition at line 57 of file csr_sparse_mat.hpp.
                                      {
    idx_.clear();
    val_.clear();
    ptr_.clear();
    idx_.reserve(Idx_len);
    val_.reserve(Idx_len);
    ptr_.reserve(ptr_len);
    ptr_.push_back(0);
  }
Multiply()
template<typename T >
void mat::CsrMat< T >::Multiply (std::vector< T > & x, std::vector< T > & r) [inline], [override], [virtual]
Implements mat::SparseMat< T >.
Definition at line 36 of file csr_sparse_mat.hpp.
                                                           {
#pragma omp parallel for shared(r, x)
        for (int i = 0; i < this->row(); ++i) {
      r[i] = T();
      for (int j = ptr_[i]; j < ptr_[i + 1]; ++j) {
        r[i] += val_.at(j) * x.at(idx_.at(j));
      }
    }
  }
References mat::SparseMat< T >::row().
MultiplyMpi()
template<typename T >
void mat::CsrMat< T >::MultiplyMpi (std::vector< T > & x, std::vector< T > & r) [inline]
Definition at line 46 of file csr_sparse_mat.hpp.
                                                     {
    this->mpi_.Allocate(x);
#pragma omp parallel for shared(r, x)
    for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i) {
      r[i] = T();
      for (int j = ptr_[i]; j < ptr_[i + 1]; ++j) {
        r[i] += val_[j] * x[idx_[j]];
      }
    }
  }
References mat::MpiVectorTool::Allocate(), mat::MpiVectorTool::beg(), mat::MpiVectorTool::end(), and mat::SparseMat< T >::mpi_.
resize() [1/2]
template<typename T >
void mat::CsrMat< T >::resize (int n) [inline]
Definition at line 31 of file csr_sparse_mat.hpp.
                     {
    this->Construct(n, n);
    SelfConstruct();
  }
References mat::SparseMat< T >::Construct().
resize() [2/2]
template<typename T >
void mat::CsrMat< T >::resize (int rows, int cols) [inline]
Definition at line 26 of file csr_sparse_mat.hpp.
                                  {
    this->Construct(rows, cols);
    this->SelfConstruct();
  }
References mat::SparseMat< T >::Construct().
Referenced by mat::CsrMat< T >::Set().
Set()
template<typename T >
void mat::CsrMat< T >::Set (const typename SparseMat< T >::CSR_type & csr) [inline]
Definition at line 69 of file csr_sparse_mat.hpp.
                                                     {
    std::tie(ptr_, idx_, val_) = csr;
    auto len = ptr_.size() - 1;
    this->resize(len, len);
    // CSR can't not received the information regarding the number
    // of cols! So, it assume the cols_ = row;
  }
References mat::CsrMat< T >::resize().
Referenced by mat::CsrMat< T >::CsrMat(), TEST(), TEST(), TEST(), TEST(), and TEST().
Show()
template<typename T >
void mat::CsrMat< T >::Show () [inline]
Definition at line 77 of file csr_sparse_mat.hpp.
                     {
    std::cout << "\n|prt\n";
    for (auto v : ptr_) {
      std::cout << v << ", ";
    }
    std::cout << "\n|Idx\n";
    for (auto v : idx_) {
      std::cout << v << ", ";
    }
    std::cout << "\n|val\n";
    for (auto v : val_) {
      std::cout << v << ", ";
    }
    std::cout << std::endl;
  }
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/csr_sparse_mat.hpp