StaggeredVelocity Class Reference
#include <physical_variables.hpp>
Public Member Functions
StaggeredVelocity (StructuredGrid &grid)
double & VisEff (int i, int j, int k)
template<typename T >
double & U (T i, T j, T k)
template<typename T >
auto & V (T i, T j, T k)
template<typename T >
auto & W (T i, T j, T k)
template<typename T >
auto U (T i, T j, T k) const
template<typename T >
auto V (T i, T j, T k) const
template<typename T >
double W (T i, T j, T k) const
template<typename T >
std::vector< double > & U (T whichDim)
void FillVel (double ui, double vi, double wi)
auto GetGrid ()
Public Member Functions inherited from PhysicalVal
PhysicalVal (StructuredGrid &grid)
Public Attributes
std::vector< double > u
std::vector< double > v
std::vector< double > w
Additional Inherited Members
Protected Member Functions inherited from PhysicalVal
template<typename T >
size_t icelCal (T i, T j, T k) const
template<typename T >
size_t icel (T i, T j, T k) const
void Fill (std::vector< double > &v, double val)
Protected Attributes inherited from PhysicalVal
StructuredGrid * grid_
Detailed Description
Definition at line 45 of file physical_variables.hpp.
Constructor & Destructor Documentation
StaggeredVelocity()
StaggeredVelocity::StaggeredVelocity (StructuredGrid & grid)
Definition at line 7 of file physical_variables.cpp.
                                                         :
    PhysicalVal(grid) {
    u.resize(grid.no_grid);
    v.resize(grid.no_grid);
    w.resize(grid.no_grid);
    vis_eff_.resize(grid.cal_no_grid);
}
References StructuredGrid::cal_no_grid, StructuredGrid::no_grid, u, v, and w.
Member Function Documentation
FillVel()
void StaggeredVelocity::FillVel (double ui, double vi, double wi) [inline]
Definition at line 98 of file physical_variables.hpp.
                                                {
    Fill(u, ui);
    Fill(v, vi);
    Fill(w, wi);
  }
References PhysicalVal::Fill(), u, v, and w.
Referenced by projection_method::CpuOpenMp::CpuOpenMp(), and projection_method::CpuOpenMpMpi::CpuOpenMpMpi().
GetGrid()
auto StaggeredVelocity::GetGrid () [inline]
Definition at line 104 of file physical_variables.hpp.
                 {
    return grid_;
  }
References PhysicalVal::grid_.
U() [1/3]
template<typename T >
double & StaggeredVelocity::U (T i, T j, T k) [inline]
Definition at line 57 of file physical_variables.hpp.
                           {
    return u[icel(i, j, k)];
  }
References PhysicalVal::icel(), and u.
Referenced by PressureMat::CalMatB(), CalSmagorinskyModel(), getCentProfile(), RemoveVelocity(), and UpdateForceAndVelocity().
U() [2/3]
template<typename T >
auto StaggeredVelocity::U (T i, T j, T k) const [inline]
Definition at line 72 of file physical_variables.hpp.
                              {
    return u[icel(i, j, k)];
  }
References PhysicalVal::icel(), and u.
U() [3/3]
template<typename T >
std::vector< double > & StaggeredVelocity::U (T whichDim) [inline]
Definition at line 87 of file physical_variables.hpp.
                                   {
    if (whichDim == 0) {
      return u;
    } else if (whichDim == 1) {
      return v;
    } else if (whichDim == 2) {
      return w;
    }
    throw std::runtime_error("out of dimensions!");
  }
References u, v, and w.
V() [1/2]
template<typename T >
auto & StaggeredVelocity::V (T i, T j, T k) [inline]
Definition at line 62 of file physical_variables.hpp.
                         {
    return v[icel(i, j, k)];
  }
References PhysicalVal::icel(), and v.
Referenced by PressureMat::CalMatB(), CalSmagorinskyModel(), getCentProfile(), RemoveVelocity(), and UpdateForceAndVelocity().
V() [2/2]
template<typename T >
auto StaggeredVelocity::V (T i, T j, T k) const [inline]
Definition at line 77 of file physical_variables.hpp.
                              {
    return v[icel(i, j, k)];
  }
References PhysicalVal::icel(), and v.
VisEff()
double & StaggeredVelocity::VisEff (int i, int j, int k) [inline]
Definition at line 50 of file physical_variables.hpp.
                                     {
    return vis_eff_[icelCal(i, j, k)];
  }
References PhysicalVal::icelCal().
Referenced by CalConvectionAndDiffusion(), and CalSmagorinskyModel().
W() [1/2]
template<typename T >
auto & StaggeredVelocity::W (T i, T j, T k) [inline]
Definition at line 67 of file physical_variables.hpp.
                         {
    return w[icel(i, j, k)];
  }
References PhysicalVal::icel(), and w.
Referenced by PressureMat::CalMatB(), CalSmagorinskyModel(), RemoveVelocity(), and UpdateForceAndVelocity().
W() [2/2]
template<typename T >
double StaggeredVelocity::W (T i, T j, T k) const [inline]
Definition at line 82 of file physical_variables.hpp.
                                {
    return w[icel(i, j, k)];
  }
References PhysicalVal::icel(), and w.
Member Data Documentation
u
std::vector<double> StaggeredVelocity::u
Definition at line 54 of file physical_variables.hpp.
Referenced by BC_updateSlid(), CalConvectionAndDiffusion(), CopyVelocityOnBoundary(), FillVel(), StaggeredVelocity(), U(), U(), U(), UpdateAllVelocityOnBoundary(), and WriteQfile().
v
std::vector<double> StaggeredVelocity::v
Definition at line 54 of file physical_variables.hpp.
Referenced by BC_updateSlid(), CalConvectionAndDiffusion(), CopyVelocityOnBoundary(), FillVel(), StaggeredVelocity(), U(), UpdateAllVelocityOnBoundary(), V(), V(), and WriteQfile().
w
std::vector<double> StaggeredVelocity::w
Definition at line 54 of file physical_variables.hpp.
Referenced by BC_updateSlid(), CalConvectionAndDiffusion(), CopyVelocityOnBoundary(), FillVel(), StaggeredVelocity(), U(), UpdateAllVelocityOnBoundary(), W(), W(), and WriteQfile().
The documentation for this class was generated from the following files:
cfd_mx/inc/backend/physical_variables.hpp
cfd_mx/src/backend/physical_variables.cpp