projection_method::CpuOpenMp Class Reference
#include <run_cpu.hpp>
Public Member Functions
CpuOpenMp (Simulation &simu, StructuredGrid &grid)
void solve ()
Detailed Description
Definition at line 27 of file run_cpu.hpp.
Constructor & Destructor Documentation
CpuOpenMp()
projection_method::CpuOpenMp::CpuOpenMp (Simulation & simu, StructuredGrid & grid) [inline]
Definition at line 29 of file run_cpu.hpp.
      : simu_(simu),
        grid_(&grid),
        vel_(StaggeredVelocity(grid)),
        intermediate_vel_(StaggeredVelocity(grid)),
        dfib_(ImmersedBoundary(grid)),
        pressure_(Pressure(grid)),
        pressure_mat_(PressureMat(grid)),
        global_domain_(grid) {
    vel_.FillVel(simu.ini_condition.u, simu.ini_condition.v, simu.ini_condition.w);
    CreatOutputFile();
    PrintIsOpenmpExist();
    std::vector<int> grid_size{grid.nx, grid.ny, grid.nz};
    global_domain_.Init({1, 1, 1}, {0, 0, 0});
    int ompThreads = omp_get_max_threads();
    omp_set_num_threads(ompThreads);
    vel_ = intermediate_vel_ = vel_;
    csv::WriteCsvFile("Information/gA.csv", *grid_);
    plot3d::write_xfile(grid);
    UpdateAllVelocityOnBoundary(global_domain_, vel_, pressure_, grid);
    CopyVelocityOnBoundary(global_domain_, vel_, intermediate_vel_, grid);
  }
References CopyVelocityOnBoundary(), CreatOutputFile(), StaggeredVelocity::FillVel(), Simulation::ini_condition, LocalDomain::Init(), StructuredGrid::nx, StructuredGrid::ny, StructuredGrid::nz, PrintIsOpenmpExist(), IniCondition::u, UpdateAllVelocityOnBoundary(), IniCondition::v, IniCondition::w, plot3d::write_xfile(), and csv::WriteCsvFile().
Member Function Documentation
solve()
void projection_method::CpuOpenMp::solve () [inline]
Definition at line 52 of file run_cpu.hpp.
              {
    pressure_solver_ = solverType(pressure_mat_.mat_a);
    pressure_solver_.SetTolerance(simu_.poisson_criteria);
    CreatEta();
    WriteQfile(dfib_, simu_, pressure_, vel_, *grid_);
    for (; !simu_.tva.IsLoopFinish(); simu_.tva.AddLoop()) {
      CalProjectionMethod();
    }
  }
References TimeVarianceAuthority::AddLoop(), TimeVarianceAuthority::IsLoopFinish(), PressureMat::mat_a, Simulation::poisson_criteria, solver::BicgstabRestart< matrixT >::SetTolerance(), Simulation::tva, and WriteQfile().
The documentation for this class was generated from the following file:
cfd_mx/inc/run/run_cpu.hpp