PressureMat Class Reference
#include <pressure_mat.hpp>
Public Member Functions
PressureMat (StructuredGrid &grid)
void ConvertResultToPressure (Pressure &pressure, const LocalDomain &domain)
void CalMatB (StaggeredVelocity &curr_vel, double dt, const LocalDomain &domain)
Public Attributes
std::vector< double > mat_b
std::vector< double > x_result
MatType mat_a
Detailed Description
Definition at line 12 of file pressure_mat.hpp.
Constructor & Destructor Documentation
PressureMat()
PressureMat::PressureMat (StructuredGrid & grid) [inline]
Definition at line 18 of file pressure_mat.hpp.
                                     : grid_(&grid) {
    mat_b.resize(grid_->cal_no_grid);
    x_result.resize(grid_->cal_no_grid, 0.0);
    mat_a.Set(GetCsrMat(grid));
  }
References StructuredGrid::cal_no_grid, GetCsrMat(), mat_a, mat_b, and x_result.
Member Function Documentation
CalMatB()
void PressureMat::CalMatB (StaggeredVelocity & curr_vel, double dt, const LocalDomain & domain) [inline]
Definition at line 33 of file pressure_mat.hpp.
                                                                                 {
    double ddt = 1.0 / dt;
#pragma omp parallel for
    for (auto i = domain.x_start; i < domain.x_end; ++i) {
      for (auto j = domain.y_start; j < domain.y_end; ++j) {
        for (auto k = domain.z_start; k < domain.z_end; ++k) {
          auto row = grid_->icelCal(i, j, k);
          mat_b[row] =
              -ddt *
              ((curr_vel.U(i, j, k) - curr_vel.U(i - 1, j, k)) / grid_->dx[i] +
               (curr_vel.V(i, j, k) - curr_vel.V(i, j - 1, k)) / grid_->dy[j] +
               (curr_vel.W(i, j, k) - curr_vel.W(i, j, k - 1)) / grid_->dz[k]);
        }
      }
    }
  }
References StructuredGrid::dx, StructuredGrid::dy, StructuredGrid::dz, StructuredGrid::icelCal(), mat_b, StaggeredVelocity::U(), StaggeredVelocity::V(), StaggeredVelocity::W(), LocalDomain::x_end, LocalDomain::x_start, LocalDomain::y_end, LocalDomain::y_start, LocalDomain::z_end, and LocalDomain::z_start.
ConvertResultToPressure()
void PressureMat::ConvertResultToPressure (Pressure & pressure, const LocalDomain & domain) [inline]
Definition at line 24 of file pressure_mat.hpp.
                                                                              {
#pragma omp parallel for
    for (size_t i = domain.x_start; i < domain.x_end; ++i)
      for (size_t j = domain.y_start; j < domain.y_end; ++j)
        for (size_t k = domain.z_start; k < domain.z_end; ++k) {
          pressure(i, j, k) = x_result[grid_->icelCal(i, j, k)];
        }
  }
References StructuredGrid::icelCal(), LocalDomain::x_end, x_result, LocalDomain::x_start, LocalDomain::y_end, LocalDomain::y_start, LocalDomain::z_end, and LocalDomain::z_start.
Member Data Documentation
mat_a
MatType PressureMat::mat_a
Definition at line 16 of file pressure_mat.hpp.
Referenced by projection_method::CpuOpenMpMpi::CpuOpenMpMpi(), PressureMat(), projection_method::CpuOpenMp::solve(), and projection_method::CpuOpenMpMpi::solve().
mat_b
std::vector<double> PressureMat::mat_b
Definition at line 14 of file pressure_mat.hpp.
Referenced by CalMatB(), and PressureMat().
x_result
std::vector<double> PressureMat::x_result
Definition at line 15 of file pressure_mat.hpp.
Referenced by ConvertResultToPressure(), Pressure_transform_X_result_Dir(), and PressureMat().
The documentation for this class was generated from the following file:
cfd_mx/inc/pressure/pressure_mat.hpp