mat::SPE_matrix1< T > Class Template Reference
#include <optimal_spe_mat.hpp>
Public Member Functions
SPE_matrix1 ()
SPE_matrix1 (StructuredGrid &grid)
void resize (int nx, int ny, int nz)
virtual ~SPE_matrix1 ()
void Init (int gC, const std::vector< double > &Dx, const std::vector< double > &Dy, const std::vector< double > &Dz, const std::vector< double > &Dxs, const std::vector< double > &Dys, const std::vector< double > &Dzs)
void Multiply (std::vector< double > &x, std::vector< double > &r)
void MultiplyMpi (std::vector< double > &x, std::vector< double > &r)
int row () const
int col () cosnt
Detailed Description
template<typename T>
class mat::SPE_matrix1< T >
Definition at line 7 of file optimal_spe_mat.hpp.
Constructor & Destructor Documentation
SPE_matrix1() [1/2]
template<typename T >
mat::SPE_matrix1< T >::SPE_matrix1 () [inline]
Definition at line 13 of file optimal_spe_mat.hpp.
{}
SPE_matrix1() [2/2]
template<typename T >
mat::SPE_matrix1< T >::SPE_matrix1 (StructuredGrid & grid) [inline]
Definition at line 14 of file optimal_spe_mat.hpp.
{construct(nx, ny, nz);}
~SPE_matrix1()
template<typename T >
virtual mat::SPE_matrix1< T >::~SPE_matrix1 () [inline], [virtual]
Definition at line 16 of file optimal_spe_mat.hpp.
{ destruct(); };
Member Function Documentation
col()
template<typename T >
int mat::SPE_matrix1< T >::col () [inline]
Definition at line 154 of file optimal_spe_mat.hpp.
{return ndim_;}
Referenced by mat::SPE_matrix1< T >::Init(), mat::SPE_matrix1< T >::Multiply(), and mat::SPE_matrix1< T >::MultiplyMpi().
Init()
template<typename T >
void mat::SPE_matrix1< T >::Init (int gC, const std::vector< double > & Dx, const std::vector< double > & Dy, const std::vector< double > & Dz, const std::vector< double > & Dxs, const std::vector< double > & Dys, const std::vector< double > & Dzs) [inline]
Definition at line 18 of file optimal_spe_mat.hpp.
         {
            // ----------------
            xp_.resize(ndim_);
            yp_.resize(ndim_);
            zp_.resize(ndim_);
            // ----------------
            // ----------------
            xm_.resize(ndim_);
            ym_.resize(ndim_);
            zm_.resize(ndim_);
            // ----------------
            gC_ = gC;
            #pragma omp parallel for schedule(static)
            for (int i=0; i<nx_; ++i)
            for (int j=0; j<ny_; ++j)
            for (int k=0; k<nz_; ++k)
            {
                xp_[i]= 1.0 /Dx[i+gC] / Dxs[i+gC];
                xm_[i]= 1.0 /Dx[i+gC] / Dxs[i+gC-1];
                yp_[j]= 1.0 /Dy[j+gC] / Dys[j+gC];
                ym_[j]= 1.0 /Dy[j+gC] / Dys[j+gC-1];
                zp_[k]= 1.0 /Dz[k+gC] / Dzs[k+gC];
                zm_[k]= 1.0 /Dz[k+gC] / Dzs[k+gC-1];
            }
            #pragma omp parallel for schedule(static)
            for (int i=0; i<nx_; ++i)
            {
                for (int j=0; j<ny_; ++j)
                {
                    for (int k=0; k<nz_; ++k)
                    {
                        int ic = k + j*nz_ + i*nynz_;
                        auto ijk = xm_[i] + ym_[j] + zm_[k] +
                                    xp_[i] + yp_[j] + zp_[k] ;
                        if (i==0) { ijk -= xm_[i]; }
                        if (i==nx_-1) { ijk -= xp_[i]; }
                        if (j==0) { ijk -= ym_[j]; }
                        if (j==ny_-1) { ijk -= yp_[j]; }
                        if (k==0) { ijk -= zm_[k]; }
                        if (k==nz_-1) { ijk -= zp_[k]; }
                        val_[ic] = ijk;
                    }
                }
            }
        }
References mat::SPE_matrix1< T >::col().
Multiply()
template<typename T >
void mat::SPE_matrix1< T >::Multiply (std::vector< double > & x, std::vector< double > & r) [inline]
Definition at line 84 of file optimal_spe_mat.hpp.
                                                                         {
#pragma omp parallel for schedule(static)
            for (int i = 0; i < nx_; ++i)
                for (int j = 0; j < ny_; ++j)
                    for (int k = 0; k < nz_; ++k) {
                        int ic = k + j * nz_ + i * nynz_;
                        double sum{0.0};
                        if (i != 0) {
                          sum += -xm_[i] * x[ic - nynz_];
                        }
                        if (j != 0) {
                          sum += -ym_[j] * x[ic - nz_];
                        }
                        if (k != 0) {
                          sum += -zm_[k] * x[ic - 1];
                        }
                        sum += val_[ic] * x[ic];
                        if (k != nz_ - 1) {
                          sum += -zp_[k] * x[ic + 1];
                        }
                        if (j != ny_ - 1) {
                          sum += -yp_[j] * x[ic + nz_];
                        }
                        if (i != nx_ - 1) {
                          sum += -xp_[i] * x[ic + nynz_];
                        }
                        r[ic] = sum;
                    }
        }
References mat::SPE_matrix1< T >::col().
MultiplyMpi()
template<typename T >
void mat::SPE_matrix1< T >::MultiplyMpi (std::vector< double > & x, std::vector< double > & r) [inline]
Definition at line 114 of file optimal_spe_mat.hpp.
                                                                            {
            mpi_.Allocate(x);
#pragma omp parallel for schedule(static)
            for (auto ic = mpi_.beg(); ic < mpi_.end(); ic++) {
            auto [i, rem] = div(ic, nynz_);
            auto [j, k] = div(rem, ny_);
            int ic = k + j * nz_ + i * nynz_;
            if (ic < mpi_.beg() || i >= mpi_.end()) continue;
            double sum{0.0};
            if (i != 0) {
            sum += -xm_[i] * x[ic - nynz_];
            }
            if (j != 0) {
            sum += -ym_[j] * x[ic - nz_];
            }
            if (k != 0) {
            sum += -zm_[k] * x[ic - 1];
            }
            sum += x[ic];
            if (k != nz_ - 1) {
            sum += -zp_[k] * x[ic + 1];
            }
            if (j != ny_ - 1) {
            sum += -yp_[j] * x[ic + nz_];
            }
            if (i != nx_ - 1) {
            sum += -xp_[i] * x[ic + nynz_];
            }
            r[ic] = sum;
            }
        }
References mat::SPE_matrix1< T >::col().
resize()
template<typename T >
void mat::SPE_matrix1< T >::resize (int nx, int ny, int nz) [inline]
Definition at line 15 of file optimal_spe_mat.hpp.
{construct(nx, ny, nz);}
row()
template<typename T >
int mat::SPE_matrix1< T >::row () const [inline]
Definition at line 153 of file optimal_spe_mat.hpp.
{return ndim_;}
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/optimal_spe_mat.hpp