ImmersedBoundary Class Reference
#include <physical_variables.hpp>
Public Member Functions
ImmersedBoundary (StructuredGrid &grid)
template<typename T >
auto Fx (T i, T j, T k) const
template<typename T >
auto Fy (T i, T j, T k) const
template<typename T >
auto Fz (T i, T j, T k) const
template<typename T >
auto Eta (T i, T j, T k) const
template<typename T >
auto & Fx (T i, T j, T k)
template<typename T >
auto & Fy (T i, T j, T k)
template<typename T >
auto & Fz (T i, T j, T k)
template<typename T >
auto & Eta (T i, T j, T k)
Public Member Functions inherited from PhysicalVal
PhysicalVal (StructuredGrid &grid)
Public Attributes
std::vector< double > f
std::vector< double > eta
std::vector< double > Val_sumz
std::vector< double > Val_sumz_sumy
std::vector< double > ValSum
std::vector< double > cylinderCenter
Additional Inherited Members
Protected Member Functions inherited from PhysicalVal
template<typename T >
size_t icelCal (T i, T j, T k) const
template<typename T >
size_t icel (T i, T j, T k) const
void Fill (std::vector< double > &v, double val)
Protected Attributes inherited from PhysicalVal
StructuredGrid * grid_
Detailed Description
Definition at line 132 of file physical_variables.hpp.
Constructor & Destructor Documentation
ImmersedBoundary()
ImmersedBoundary::ImmersedBoundary (StructuredGrid & grid)
Definition at line 15 of file physical_variables.cpp.
                                                      :
    PhysicalVal(grid) {
    eta.resize(grid_->no_grid);
    f.resize(grid_->cal_no_grid * 3);
    yShift_ = grid_->cal_no_grid;
    zShift_ = 2 * grid_->cal_no_grid;
}
References StructuredGrid::cal_no_grid, eta, f, PhysicalVal::grid_, and StructuredGrid::no_grid.
Member Function Documentation
Eta() [1/2]
template<typename T >
auto & ImmersedBoundary::Eta (T i, T j, T k) [inline]
Definition at line 176 of file physical_variables.hpp.
                           {
    return eta[icel(i, j, k)];
  }
References eta, and PhysicalVal::icel().
Eta() [2/2]
template<typename T >
auto ImmersedBoundary::Eta (T i, T j, T k) const [inline]
Definition at line 156 of file physical_variables.hpp.
                                {
    return eta[icel(i, j, k)];
  }
References eta, and PhysicalVal::icel().
Referenced by RemoveVelocity(), CylinderZ::solver(), and UpdateForceAndVelocity().
Fx() [1/2]
template<typename T >
auto & ImmersedBoundary::Fx (T i, T j, T k) [inline]
Definition at line 161 of file physical_variables.hpp.
                          {
    return f[icelCal(i, j, k)];
  }
References f, and PhysicalVal::icelCal().
Fx() [2/2]
template<typename T >
auto ImmersedBoundary::Fx (T i, T j, T k) const [inline]
Definition at line 141 of file physical_variables.hpp.
                               {
    return f[icelCal(i, j, k)];
  }
References f, and PhysicalVal::icelCal().
Referenced by UpdateForceAndVelocity().
Fy() [1/2]
template<typename T >
auto & ImmersedBoundary::Fy (T i, T j, T k) [inline]
Definition at line 166 of file physical_variables.hpp.
                          {
    return f[icelCal(i, j, k) + yShift_];
  }
References f, and PhysicalVal::icelCal().
Fy() [2/2]
template<typename T >
auto ImmersedBoundary::Fy (T i, T j, T k) const [inline]
Definition at line 146 of file physical_variables.hpp.
                               {
    return f[icelCal(i, j, k) + yShift_];
  }
References f, and PhysicalVal::icelCal().
Referenced by UpdateForceAndVelocity().
Fz() [1/2]
template<typename T >
auto & ImmersedBoundary::Fz (T i, T j, T k) [inline]
Definition at line 171 of file physical_variables.hpp.
                          {
    return f[icelCal(i, j, k) + zShift_];
  }
References f, and PhysicalVal::icelCal().
Fz() [2/2]
template<typename T >
auto ImmersedBoundary::Fz (T i, T j, T k) const [inline]
Definition at line 151 of file physical_variables.hpp.
                               {
    return f[icelCal(i, j, k) + zShift_];
  }
References f, and PhysicalVal::icelCal().
Referenced by UpdateForceAndVelocity().
Member Data Documentation
cylinderCenter
std::vector<double> ImmersedBoundary::cylinderCenter
Definition at line 184 of file physical_variables.hpp.
eta
std::vector<double> ImmersedBoundary::eta
Definition at line 180 of file physical_variables.hpp.
Referenced by Eta(), Eta(), ImmersedBoundary(), and WriteQfile().
f
std::vector<double> ImmersedBoundary::f
Definition at line 180 of file physical_variables.hpp.
Referenced by Fx(), Fx(), Fy(), Fy(), Fz(), Fz(), ImmersedBoundary(), and virtualF_Int().
Val_sumz
std::vector<double> ImmersedBoundary::Val_sumz
Definition at line 181 of file physical_variables.hpp.
Val_sumz_sumy
std::vector<double> ImmersedBoundary::Val_sumz_sumy
Definition at line 182 of file physical_variables.hpp.
ValSum
std::vector<double> ImmersedBoundary::ValSum
Definition at line 183 of file physical_variables.hpp.
Referenced by Delay_IO_CD_CL(), getCD_CL_mpi(), noDelay_IO_CD_CL(), and virtualF_Int().
The documentation for this class was generated from the following files:
cfd_mx/inc/backend/physical_variables.hpp
cfd_mx/src/backend/physical_variables.cpp