mat::StructGridMat< T > Class Template Reference
#include <spe_mat.hpp>
Public Member Functions
StructGridMat ()
StructGridMat (int cal_nx, int cal_ny, int cal_nz)
void resize (int cal_nx, int cal_ny, int cal_nz)
int row () const
int col () const
void Init (int gC, const std::vector< double > &Dx, const std::vector< double > &Dy, const std::vector< double > &Dz, const std::vector< double > &Dxs, const std::vector< double > &Dys, const std::vector< double > &Dzs)
void Multiply (std::vector< double > &x, std::vector< double > &r)
void mpi_init (MPI_Comm comm_world, int total)
auto GetMpi () const
void MultiplyMpi (std::vector< T > &x, std::vector< T > &r)
Detailed Description
template<typename T>
class mat::StructGridMat< T >
Definition at line 23 of file spe_mat.hpp.
Constructor & Destructor Documentation
StructGridMat() [1/2]
template<typename T >
mat::StructGridMat< T >::StructGridMat () [inline]
Definition at line 26 of file spe_mat.hpp.
{}
StructGridMat() [2/2]
template<typename T >
mat::StructGridMat< T >::StructGridMat (int cal_nx, int cal_ny, int cal_nz) [inline]
Definition at line 28 of file spe_mat.hpp.
{ construct(cal_nx, cal_ny, cal_nz); }
Member Function Documentation
col()
template<typename T >
int mat::StructGridMat< T >::col () const [inline]
Definition at line 32 of file spe_mat.hpp.
{ return ndim_; }
Referenced by mat::StructGridMat< T >::Init(), mat::StructGridMat< T >::mpi_init(), mat::StructGridMat< T >::Multiply(), and mat::StructGridMat< T >::MultiplyMpi().
GetMpi()
template<typename T >
auto mat::StructGridMat< T >::GetMpi () const [inline]
Definition at line 97 of file spe_mat.hpp.
{return mpi_;}
Init()
template<typename T >
void mat::StructGridMat< T >::Init (int gC, const std::vector< double > & Dx, const std::vector< double > & Dy, const std::vector< double > & Dz, const std::vector< double > & Dxs, const std::vector< double > & Dys, const std::vector< double > & Dzs) [inline]
Definition at line 34 of file spe_mat.hpp.
                                              {
#pragma omp parallel for schedule(static)
            for (int i=0; i<nx_; ++i)
            {
                for (int j=0; j<ny_; ++j)
                {
                    for (int k=0; k<nz_; ++k)
                    {
                        auto xp = [&](auto i){return 1.0/Dx.at(i+gC)/Dxs.at(i+gC);};
                        auto yp = [&](auto j){return 1.0/Dy.at(j+gC)/Dys.at(j+gC);};
                        auto zp = [&](auto k){return 1.0/Dz.at(k+gC)/Dzs.at(k+gC);};
                        auto xm = [&](auto i){return 1.0/Dx.at(i+gC)/Dxs.at(i+gC-1);};
                        auto ym = [&](auto j){return 1.0/Dy.at(j+gC)/Dys.at(j+gC-1);};
                        auto zm = [&](auto k){return 1.0/Dz.at(k+gC)/Dzs.at(k+gC-1);};
                        int ic = k + j*nz_ + i*nynz_;
                        auto ic7 = ic*7;
                        auto ijk = xm(i) + ym(j) + zm(k) +
                                    xp(i) + yp(j) + zp(k) ;
                        
                        if (i==0) { ijk -= xm(i); }
                        if (i==nx_-1) { ijk -= xp(i); }
                        if (j==0) { ijk -= ym(j); }
                        if (j==ny_-1) { ijk -= yp(j); }
                        if (k==0) { ijk -= zm(k); }
                        if (k==nz_-1) { ijk -= zp(k); }
                        if (i!=0) { val_[ic7+ 0] = -xm(i); }else{ val_[ic7+ 0] = T(); }
                        if (j!=0) { val_[ic7+ 1] = -ym(j); }else{ val_[ic7+ 1] = T(); }
                        if (k!=0) { val_[ic7+ 2] = -zm(k); }else{ val_[ic7+ 2] = T(); }
                                        val_[ic7+ 3] = ijk;
                        if (k!=nz_-1) { val_[ic7+ 4] = -zp(k); }else{ val_[ic7+ 4] = T(); }
                        if (j!=ny_-1) { val_[ic7+ 5] = -yp(j); }else{ val_[ic7+ 5] = T(); }
                        if (i!=nx_-1) { val_[ic7+ 6] = -xp(i); }else{ val_[ic7+ 6] = T(); }
                    }
                }
            }
      }
References mat::StructGridMat< T >::col().
mpi_init()
template<typename T >
void mat::StructGridMat< T >::mpi_init (MPI_Comm comm_world, int total) [inline]
Definition at line 94 of file spe_mat.hpp.
            { mpi_.init(comm_world, total); }
References mat::StructGridMat< T >::col().
Multiply()
template<typename T >
void mat::StructGridMat< T >::Multiply (std::vector< double > & x, std::vector< double > & r) [inline]
Definition at line 78 of file spe_mat.hpp.
                                                                         {
#pragma omp parallel for schedule(static)
            for (int i = 0; i < ndim_ ; ++i){
                double sum {0.0};
                auto i7 = i * 7;
                if (i-nynz_ >= 0) { sum += val_[i7+0] * x[i-nynz_]; }
                if (i-nz_ >= 0) { sum += val_[i7+1] * x[i-nz_ ]; }
                if (i-1 >= 0) { sum += val_[i7+2] * x[i-1 ]; }
                                          sum += val_[i7+3] * x[i ];
                if (i+1 < ndim_) { sum += val_[i7+4] * x[i+1 ]; }
                if (i+nz_ < ndim_) { sum += val_[i7+5] * x[i+nz_ ]; }
                if (i+nynz_ < ndim_) { sum += val_[i7+6] * x[i+nynz_]; }
                r[i] = sum;
            }
        }
References mat::StructGridMat< T >::col().
MultiplyMpi()
template<typename T >
void mat::StructGridMat< T >::MultiplyMpi (std::vector< T > & x, std::vector< T > & r) [inline]
Definition at line 99 of file spe_mat.hpp.
                                                                  {
            mpi_.Allocate(x);
            for (auto i = mpi_.beg(); i < mpi_.end(); ++i) {
                double sum = 0.0;
                auto i7 = i * 7;
                if (i - nynz_ >= 0) {
                    sum += val_[i7 + 0] * x[i - nynz_];
                }
                if (i - nz_ >= 0) {
                    sum += val_[i7 + 1] * x[i - nz_];
                }
                if (i - 1 >= 0) {
                    sum += val_[i7 + 2] * x[i - 1];
                }
                sum += val_[i7 + 3] * x[i];
                if (i + 1 < ndim_) {
                    sum += val_[i7 + 4] * x[i + 1];
                }
                if (i + nz_ < ndim_) {
                    sum += val_[i7 + 5] * x[i + nz_];
                }
                if (i + nynz_ < ndim_) {
                    sum += val_[i7 + 6] * x[i + nynz_];
                }
                r[i] = sum;
            }
        }
References mat::StructGridMat< T >::col().
resize()
template<typename T >
void mat::StructGridMat< T >::resize (int cal_nx, int cal_ny, int cal_nz) [inline]
Definition at line 30 of file spe_mat.hpp.
{ construct(cal_nx, cal_ny, cal_nz); }
row()
template<typename T >
int mat::StructGridMat< T >::row () const [inline]
Definition at line 31 of file spe_mat.hpp.
{ return ndim_; }
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/spe_mat.hpp