solver::BicgstabRestartMpi< matrixT > Class Template Reference
#include <bicgstab_restart_mpi.hpp>
Public Member Functions
BicgstabRestartMpi ()
BicgstabRestartMpi (matrixT &lhs_mat)
virtual ~BicgstabRestartMpi ()
void init (matrixT lhs_mat)
void SetTolerance (double tolerance)
std::tuple< int, double > solve (const std::vector< double > &rhs, std::vector< double > &x)
std::tuple< int, double > operator() (const std::vector< double > &rhs, std::vector< double > &x)
Detailed Description
template<typename matrixT>
class solver::BicgstabRestartMpi< matrixT >
Definition at line 10 of file bicgstab_restart_mpi.hpp.
Constructor & Destructor Documentation
BicgstabRestartMpi() [1/2]
template<typename matrixT >
solver::BicgstabRestartMpi< matrixT >::BicgstabRestartMpi () [inline]
Definition at line 14 of file bicgstab_restart_mpi.hpp.
{}
BicgstabRestartMpi() [2/2]
template<typename matrixT >
solver::BicgstabRestartMpi< matrixT >::BicgstabRestartMpi (matrixT & lhs_mat) [inline]
Definition at line 16 of file bicgstab_restart_mpi.hpp.
{ init(lhs_mat);}
References solver::BicgstabRestartMpi< matrixT >::init().
~BicgstabRestartMpi()
template<typename matrixT >
virtual solver::BicgstabRestartMpi< matrixT >::~BicgstabRestartMpi () [inline], [virtual]
Definition at line 18 of file bicgstab_restart_mpi.hpp.
{ }
Member Function Documentation
init()
template<typename matrixT >
void solver::BicgstabRestartMpi< matrixT >::init (matrixT lhs_mat) [inline]
Definition at line 21 of file bicgstab_restart_mpi.hpp.
        {
            mpi_ = lhs_mat.mpi_;
            lhs_mat_ = lhs_mat;
            length_ = lhs_mat.row();
            r0_.resize(length_, 0.0);
            r1_.resize(length_, 0.0);
            p1_.resize(length_, 0.0);
            s1_.resize(length_, 0.0);
            ap_.resize(length_, 0.0);
            as_.resize(length_, 0.0);
            px1_.resize(length_, 0.0);
            px2_.resize(length_, 0.0);
        }
Referenced by solver::BicgstabRestartMpi< matrixT >::BicgstabRestartMpi().
operator()()
template<typename matrixT >
std::tuple< int, double > solver::BicgstabRestartMpi< matrixT >::operator() (const std::vector< double > & rhs, std::vector< double > & x) [inline]
Definition at line 41 of file bicgstab_restart_mpi.hpp.
                                                                 {
            return solve(rhs, x);
        }
References solver::BicgstabRestartMpi< matrixT >::solve().
SetTolerance()
template<typename matrixT >
void solver::BicgstabRestartMpi< matrixT >::SetTolerance (double tolerance) [inline]
Definition at line 36 of file bicgstab_restart_mpi.hpp.
{ tol_ = tolerance;}
Referenced by TEST(), and TEST().
solve()
template<typename matrixT >
std::tuple< int, double > solver::BicgstabRestartMpi< matrixT >::solve (const std::vector< double > & rhs, std::vector< double > & x) [inline]
Definition at line 86 of file bicgstab_restart_mpi.hpp.
                                                            {
            timestep_++;
            double r1r0 = 0, pre_r1r0 = 0, a = 0, w = 0, b = 0,
                   norm0 = mpi_.L2Norm(rhs);
            lhs_mat_.MultiplyMpi(x, r0_);
            // ---------------------------
            math::copy(px1_, px2_);
            math::copy(x, px1_);
#pragma omp parallel for default(none) shared(rhs, r0_)
            for (int i = mpi_.beg(); i < mpi_.end(); ++i) {
            r0_[i] = rhs[i] - r0_[i];
            }
            math::copy(r0_, r1_);
            math::copy(r0_, p1_);
            // ---------------------------
            r1r0 = mpi_.InnerProduct(r1_, r0_);
            int numIter_ = 0;
            while (true) {
            lhs_mat_.MultiplyMpi(p1_, ap_);
            a = r1r0 / mpi_.InnerProduct(ap_, r0_);
            mpi_.Barrier();
#pragma omp parallel for schedule(static)
                for (int i = mpi_.beg(); i < mpi_.end(); ++i) { s1_[i] = r1_[i] - a*ap_[i]; }
                mpi_.Barrier();
                lhs_mat_.MultiplyMpi(s1_, as_);
                w = mpi_.InnerProduct(as_, s1_) / mpi_.InnerProduct(as_, as_);
                for (int i = mpi_.beg(); i < mpi_.end(); ++i) {
                  x[i] += a * p1_[i] + w * s1_[i];
                  r1_[i] = s1_[i] - w * as_[i];
            }
            // Check for terminating conditions
            if ((mpi_.L2Norm(r1_) / norm0) < tol_) { break; }
            // cout << mpi_.L2Norm(r1_) / norm0 << ", ";
            // ! ## Check for reset of bCGSTAB
            if (numIter_ >= iters_max_) {
                int ResetMembers = 0;
                for(int i = mpi_.beg(); i < mpi_.end(); ++i){
                    if (std::isnan(x[i]) || std::isinf(x[i]))
                    { x[i] = px1_[i], ++ResetMembers;}
                }
                ResetMembers = mpi_.AllreduceSum(ResetMembers);
                if (ResetMembers > length_*0.1) {
                    for(int i = mpi_.beg(); i<mpi_.end(); ++i)
                    { x[i] = px2_[i]; }
                    accumulativeResetMembers_ += length_, ++pResets_;
                }
                else if (ResetMembers != 0)
                { accumulativeResetMembers_ += ResetMembers, ++pResets_; }
                break;
            }
            // *------------------------------------
            pre_r1r0 = r1r0;
            r1r0 = mpi_.InnerProduct(r1_, r0_);
            b = (a / w) * (r1r0 / pre_r1r0);
            // Check rho for restart
            if (timestep_ < 10 || abs(pre_r1r0) > restartTol_)
            {
                #pragma omp parallel for
                for(int i = mpi_.beg(); i<mpi_.end(); ++i)
                { p1_[i] = r1_[i] + b*(p1_[i] - w*ap_[i]); }
            }
            else
            {
                for(int i = mpi_.beg(); i<mpi_.end(); ++i)
                {
                    r0_[i] = r1_[i];
                    p1_[i] = r1_[i];
                }
                ++numRestarts_;
            }
            ++numIter_;
            ++totalNumIter_;
        }
        mpi_.Allocate(x);
        return std::make_tuple(numIter_, mpi_.L2Norm(r1_) / norm0);
    }
References math::copy(), and mat::MpiVectorTool::L2Norm().
Referenced by solver::BicgstabRestartMpi< matrixT >::operator()().
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/solver/mpi/bicgstab_restart_mpi.hpp