solver::BicgstabRestart< matrixT > Class Template Reference
#include <bicgstab_restart.hpp>
Public Member Functions
BicgstabRestart ()
BicgstabRestart (matrixT &lhs_mat)
virtual ~BicgstabRestart ()
void init (matrixT &lhs_mat)
void SetTolerance (double tolerance) override
std::tuple< int, double > solve (const std::vector< double > &rhs, std::vector< double > &x) override
Public Member Functions inherited from solver::LinearSolver< matrixT >
LinearSolver ()
LinearSolver (matrixT &lhs_mat)
virtual ~LinearSolver ()
void construct (const matrixT &lhs_mat)
void SetMaxIters (int niters)
std::tuple< int, double > operator() (const std::vector< double > &rhs, std::vector< double > &x)
Additional Inherited Members
Protected Member Functions inherited from solver::LinearSolver< matrixT >
double InnerProduct (const std::vector< double > &rhs, const std::vector< double > &x)
Protected Attributes inherited from solver::LinearSolver< matrixT >
matrixT lhs_mat_
double tolerance_ {1e-5}
int iters_max_ {3000}
Detailed Description
template<typename matrixT>
class solver::BicgstabRestart< matrixT >
Definition at line 9 of file bicgstab_restart.hpp.
Constructor & Destructor Documentation
BicgstabRestart() [1/2]
template<typename matrixT >
solver::BicgstabRestart< matrixT >::BicgstabRestart () [inline]
Definition at line 11 of file bicgstab_restart.hpp.
{}
BicgstabRestart() [2/2]
template<typename matrixT >
solver::BicgstabRestart< matrixT >::BicgstabRestart (matrixT & lhs_mat) [inline]
Definition at line 13 of file bicgstab_restart.hpp.
                                    : LinearSolver<matrixT>(lhs_mat) {
    init(lhs_mat);
  }
References solver::BicgstabRestart< matrixT >::init().
~BicgstabRestart()
template<typename matrixT >
virtual solver::BicgstabRestart< matrixT >::~BicgstabRestart () [inline], [virtual]
Definition at line 17 of file bicgstab_restart.hpp.
{}
Member Function Documentation
init()
template<typename matrixT >
void solver::BicgstabRestart< matrixT >::init (matrixT & lhs_mat) [inline]
Definition at line 19 of file bicgstab_restart.hpp.
                                     {
    length_ = this->lhs_mat_.row();
    r0_.resize(length_, 0.0);
    r1_.resize(length_, 0.0);
    p1_.resize(length_, 0.0);
    s1_.resize(length_, 0.0);
    ap_.resize(length_, 0.0);
    as_.resize(length_, 0.0);
    px1_.resize(length_, 0.0);
    px2_.resize(length_, 0.0);
  }
References solver::LinearSolver< matrixT >::lhs_mat_.
Referenced by solver::BicgstabRestart< matrixT >::BicgstabRestart().
SetTolerance()
template<typename matrixT >
void solver::BicgstabRestart< matrixT >::SetTolerance (double tolerance) [inline], [override], [virtual]
Reimplemented from solver::LinearSolver< matrixT >.
Definition at line 31 of file bicgstab_restart.hpp.
                                               {
    this->tolerance_ = tolerance;
    restartTol_ = pRestartFactor_ * this->tolerance_;
  }
References solver::LinearSolver< matrixT >::tolerance_.
Referenced by projection_method::CpuOpenMp::solve(), TEST(), TEST(), and TEST().
solve()
template<typename matrixT >
std::tuple< int, double > solver::BicgstabRestart< matrixT >::solve (const std::vector< double > & rhs, std::vector< double > & x) [inline], [override], [virtual]
Implements solver::LinearSolver< matrixT >.
Definition at line 36 of file bicgstab_restart.hpp.
                                                                      {
    timestep_++;
    double r1r0 = 0, pre_r1r0 = 0, a = 0, w = 0, b = 0,
           norm0 = math::L2Norm(rhs);
    this->lhs_mat_.Multiply(x, r0_);
    // ---------------------------
    math::copy(px1_, px2_);
    math::copy(x, px1_);
#pragma omp parallel for schedule(static) default(none) shared(rhs, r0_)
    for (int i = 0; i < length_; ++i) {
      r0_[i] = rhs[i] - r0_[i];
    }
    math::copy(r0_, r1_);
    math::copy(r0_, p1_);
    // ---------------------------
    r1r0 = math::InnerProduct(r1_, r0_);
    int no_iters_ = 0;
    while (true) {
      this->lhs_mat_.Multiply(p1_, ap_);
      a = r1r0 / math::InnerProduct(ap_, r0_);
#pragma omp parallel for schedule(static)
      for (int i = 0; i < length_; ++i) {
        s1_[i] = r1_[i] - a * ap_[i];
      }
      this->lhs_mat_.Multiply(s1_, as_);
      w = math::InnerProduct(as_, s1_) / math::InnerProduct(as_, as_);
#pragma omp parallel for schedule(static)
      for (int i = 0; i < length_; ++i) {
        x[i] += a * p1_[i] + w * s1_[i];
        r1_[i] = s1_[i] - w * as_[i];
      }
      // Check for terminating conditions
      if ((math::L2Norm(r1_) / norm0) < this->tolerance_) {
        break;
      }
      // ! ## Check for reset of bCGSTAB
      if (no_iters_ >= this->iters_max_) {
        int ResetMembers = 0;
#pragma omp parallel for schedule(static) reduction(+ : ResetMembers)
        for (int i = 0; i < length_; ++i) {
          if (std::isnan(x[i]) || std::isinf(x[i])) {
            x[i] = px1_[i], ++ResetMembers;
          }
        }
        if (ResetMembers > length_ * 0.1) {
          math::copy(px2_, x);
          accumulativeResetMembers_ += length_, ++pResets_;
        } else if (ResetMembers != 0) {
          accumulativeResetMembers_ += ResetMembers, ++pResets_;
        }
        break;
      }
      // *------------------------------------
      pre_r1r0 = r1r0;
      r1r0 = math::InnerProduct(r1_, r0_);
      b = (a / w) * (r1r0 / pre_r1r0);
      // Check rho for restart
      if (timestep_ < 10 || std::abs(pre_r1r0) > restartTol_) {
#pragma omp parallel for schedule(static)
        for (int i = 0; i < length_; ++i) {
          p1_[i] = r1_[i] + b * (p1_[i] - w * ap_[i]);
        }
      } else {
        math::copy(r1_, r0_);
        math::copy(r1_, p1_);
        ++numRestarts_;
      }
      ++no_iters_;
      ++total_no_iters_;
    }
    return std::make_tuple(no_iters_, math::L2Norm(r1_) / norm0);
  }
References math::copy(), math::InnerProduct(), solver::LinearSolver< matrixT >::iters_max_, math::L2Norm(), solver::LinearSolver< matrixT >::lhs_mat_, and solver::LinearSolver< matrixT >::tolerance_.
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/solver/bicgstab_restart.hpp