solver::BicgstabMpi< matrixT > Class Template Reference
#include <bicgstab_mpi.hpp>
Public Member Functions
BicgstabMpi ()
BicgstabMpi (matrixT &lhs_mat)
virtual ~BicgstabMpi ()
void init (const matrixT &lhs_mat)
std::tuple< int, double > solve (const std::vector< double > &rhs, std::vector< double > &x) override
Public Member Functions inherited from solver::LinearSolverMpi< matrixT >
LinearSolverMpi ()
LinearSolverMpi (matrixT &lhs_mat)
virtual ~LinearSolverMpi ()
void Construct (const matrixT &lhs_mat)
void SetTolerance (double tolerance)
void SetMaxIters (int niters)
std::tuple< int, double > operator() (const std::vector< double > &rhs, std::vector< double > &x)
Additional Inherited Members
Protected Member Functions inherited from solver::LinearSolverMpi< matrixT >
double InnerProduct (const std::vector< double > &rhs, const std::vector< double > &x)
Protected Attributes inherited from solver::LinearSolverMpi< matrixT >
double tolerance_
int iters_max_
matrixT lhs_mat_
mat::MpiVectorTool mpi_
Detailed Description
template<typename matrixT>
class solver::BicgstabMpi< matrixT >
Definition at line 14 of file bicgstab_mpi.hpp.
Constructor & Destructor Documentation
BicgstabMpi() [1/2]
template<typename matrixT >
solver::BicgstabMpi< matrixT >::BicgstabMpi () [inline]
Definition at line 16 of file bicgstab_mpi.hpp.
{}
BicgstabMpi() [2/2]
template<typename matrixT >
solver::BicgstabMpi< matrixT >::BicgstabMpi (matrixT & lhs_mat) [inline]
Definition at line 18 of file bicgstab_mpi.hpp.
                                    : LinearSolverMpi<matrixT>(lhs_mat) {
        init(lhs_mat);
      }
References solver::BicgstabMpi< matrixT >::init().
~BicgstabMpi()
template<typename matrixT >
virtual solver::BicgstabMpi< matrixT >::~BicgstabMpi () [inline], [virtual]
Definition at line 22 of file bicgstab_mpi.hpp.
{}
Member Function Documentation
init()
template<typename matrixT >
void solver::BicgstabMpi< matrixT >::init (const matrixT & lhs_mat) [inline]
Definition at line 24 of file bicgstab_mpi.hpp.
                                               {
        this->Construct(lhs_mat);
        length_ = this->lhs_mat_.row();
        p_.resize(length_);
        r_.resize(length_);
        r2_.resize(length_);
        v_.resize(length_);
        ss_.resize(length_);
        t_.resize(length_);
      }
References solver::LinearSolverMpi< matrixT >::Construct(), and solver::LinearSolverMpi< matrixT >::lhs_mat_.
Referenced by solver::BicgstabMpi< matrixT >::BicgstabMpi().
solve()
template<typename matrixT >
std::tuple< int, double > solver::BicgstabMpi< matrixT >::solve (const std::vector< double > & rhs, std::vector< double > & x) [inline], [override], [virtual]
Implements solver::LinearSolverMpi< matrixT >.
Definition at line 35 of file bicgstab_mpi.hpp.
                                                                          {
        int iters{0};
        double norm{0};
        double norm_rhs = this->mpi_.L2Norm(rhs);
        this->lhs_mat_.MultiplyMpi(x, p_);
        for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i)
          r_[i] = rhs[i] - p_[i];
        for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i)
          r2_[i] = r_[i];
        rho1_ = 1;
        alpha_ = 1;
        omega_ = 1;
        for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i) {
          v_[i] = 0.0;
        }
        for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i) {
          p_[i] = 0.0;
        }
        norm = this->mpi_.L2Norm(r_) / norm_rhs;
        iters = 0;
        while (norm > this->tolerance_ && iters < this->iters_max_) {
          ++iters;
          rho2_ = this->InnerProduct(r2_, r_);
          beta_ = (rho2_ / rho1_) * (alpha_ / omega_);
          for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i)
            p_[i] = r_[i] + beta_ * (p_[i] - omega_ * v_[i]);
          this->lhs_mat_.MultiplyMpi(p_, v_);
          alpha_ = rho2_ / this->InnerProduct(r2_, v_);
          for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i)
            ss_[i] = r_[i] - alpha_ * v_[i];
          this->lhs_mat_.MultiplyMpi(ss_, t_);
          omega_ = this->InnerProduct(t_, ss_) / this->InnerProduct(t_, t_);
          for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i)
            x[i] += alpha_ * p_[i] + omega_ * ss_[i];
          for (int i = this->mpi_.beg(); i < this->mpi_.end(); ++i)
            r_[i] = ss_[i] - omega_ * t_[i];
          rho1_ = rho2_;
          norm = 0;
          norm = this->InnerProduct(r_, r_);
          norm = sqrt(norm) / norm_rhs;
        }
        this->mpi_.Allocate(x);
        return std::make_tuple(iters, norm);
      }
References mat::MpiVectorTool::Allocate(), mat::MpiVectorTool::beg(), mat::MpiVectorTool::end(), solver::LinearSolverMpi< matrixT >::InnerProduct(), solver::LinearSolverMpi< matrixT >::iters_max_, mat::MpiVectorTool::L2Norm(), solver::LinearSolverMpi< matrixT >::lhs_mat_, solver::LinearSolverMpi< matrixT >::mpi_, and solver::LinearSolverMpi< matrixT >::tolerance_.
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/solver/mpi/bicgstab_mpi.hpp