mpi::MpiTool Class Reference
#include <mpi_tool.hpp>
Public Member Functions
MpiTool (int argc, char **argv, StructuredGrid &grid, int reorder=true)
void SetDomain (LocalDomain &domain)
MpiTool & Barrier ()
auto GetRank ()
auto GetSize ()
MpiTool & SendRecv (int nolayers, std::vector< double > &v)
MpiTool & ISendRecv (int nolayers, std::vector< double > &v)
MpiTool & ISendRecvRight (int nolayers, std::vector< double > &v)
MpiTool & ISendRecvLeft (int nolayers, std::vector< double > &v)
MpiTool & SendRecvLeft (int nolayers, std::vector< double > &v)
MpiTool & SendRecvRight (int nolayers, std::vector< double > &v)
MpiTool & CollectToMaster (std::vector< double > &v)
bool IsMaster ()
MPI_Comm & GetCommWorld ()
Detailed Description
Definition at line 12 of file mpi_tool.hpp.
Constructor & Destructor Documentation
MpiTool()
mpi::MpiTool::MpiTool (int argc, char ** argv, StructuredGrid & grid, int reorder = true) [inline]
Definition at line 15 of file mpi_tool.hpp.
       : grid_(&grid) {
     MPI_Init(&argc, &argv);
     rank_ = mpi::GetRank();
     size_ = mpi::GetSize();
     VirtualProcessTopology(reorder);
     no_one_layer_ = grid.nz * grid.ny;
   }
References mpi::GetRank(), mpi::GetSize(), StructuredGrid::ny, and StructuredGrid::nz.
Member Function Documentation
Barrier()
MpiTool & mpi::MpiTool::Barrier () [inline]
Definition at line 28 of file mpi_tool.hpp.
{ MPI_Barrier(comm_world_); return *this; }
Referenced by projection_method::CpuOpenMpMpi::solve().
CollectToMaster()
MpiTool & mpi::MpiTool::CollectToMaster (std::vector< double > & v) [inline]
Definition at line 132 of file mpi_tool.hpp.
                                                  {
            auto gc = grid_->no_ghost_cell;
            std::vector<int> itag;
            MPI_Request requests[(size_ - 1) * 2];
            for (size_t i_rank = 1; i_rank < size_; ++i_rank) {
              MPI_Barrier(comm_world_);
              itag.push_back(i_rank*10);
              int shift =
                  no_one_layer_ * (domain_->GetGlobal_x().start[i_rank]);
              int count =
                  no_one_layer_ * (domain_->GetGlobal_x().len[i_rank]);
              if (i_rank == size_ - 1) {
                count += no_one_layer_ * gc;
              }
              if (IsMaster()) {
                MPI_Irecv((void *)&v[shift], count, MPI_DOUBLE, i_rank,
                          itag[i_rank - 1], comm_world_,
                          requests + size_ + i_rank - 1);
              } else if (rank_ == i_rank) {
                MPI_Isend((void *)&v[shift], count, MPI_DOUBLE, master_,
                          itag[i_rank - 1], comm_world_, requests + i_rank-1);
              }
            }
            // MPI_Status status[size_];
            // MPI_Waitall(size_, requests, status);
            return *this;
   }
References LocalDomain::GetGlobal_x(), IsMaster(), GlobalDomain::len, StructuredGrid::no_ghost_cell, and GlobalDomain::start.
GetCommWorld()
MPI_Comm & mpi::MpiTool::GetCommWorld () [inline]
Definition at line 166 of file mpi_tool.hpp.
{ return comm_world_; }
Referenced by projection_method::CpuOpenMpMpi::CpuOpenMpMpi().
GetRank()
auto mpi::MpiTool::GetRank () [inline]
Definition at line 30 of file mpi_tool.hpp.
{ return rank_; }
Referenced by projection_method::CpuOpenMpMpi::CpuOpenMpMpi().
GetSize()
auto mpi::MpiTool::GetSize () [inline]
Definition at line 31 of file mpi_tool.hpp.
{ return size_; }
ISendRecv()
MpiTool & mpi::MpiTool::ISendRecv (int nolayers, std::vector< double > & v) [inline]
Definition at line 53 of file mpi_tool.hpp.
                                                           {
       auto [shift_send, shift_recv] = GetSendRecvPosition(nolayers);
       MPI_Request requests[4];
       MakeItagCntCycle();
       int itag[2] = {itag_cnt++, itag_cnt++};
       int cnt = nolayers * no_one_layer_;
       // !`+`
       MPI_Isend(&v[shift_send[0]], cnt, MPI_DOUBLE, left_neighborhood,
                 itag[0], comm_world_, requests + 0);
       MPI_Irecv(&v[shift_recv[0]], cnt, MPI_DOUBLE, right_neighborhood,
                 itag[0], comm_world_, requests + 1);
       // !`-`
       MPI_Isend(&v[shift_send[1]], cnt, MPI_DOUBLE, right_neighborhood,
                 itag[1], comm_world_, requests + 2);
       MPI_Irecv(&v[shift_recv[1]], cnt, MPI_DOUBLE, left_neighborhood,
                 itag[1], comm_world_, requests + 3);
      // MPI_Status status[1];
      // MPI_Waitall(4, requests, status);
       return *this;
    }
ISendRecvLeft()
MpiTool & mpi::MpiTool::ISendRecvLeft (int nolayers, std::vector< double > & v) [inline]
Definition at line 91 of file mpi_tool.hpp.
                                                              {
       MakeItagCntCycle();
       int itag[2] = {itag_cnt++, itag_cnt++};
       int cnt = nolayers * no_one_layer_;
       auto [shift_send, shift_recv] = GetSendRecvPosition(nolayers);
       MPI_Request requests[2];
      // MPI_Status status[1];
       MPI_Isend(&v[shift_send[1]], cnt, MPI_DOUBLE, right_neighborhood,
                 itag[1], comm_world_, requests + 0);
       MPI_Irecv(&v[shift_recv[1]], cnt, MPI_DOUBLE, left_neighborhood,
                 itag[1], comm_world_, requests + 1);
      // MPI_Waitall(2, requests, status);
       return *this;
   }
ISendRecvRight()
MpiTool & mpi::MpiTool::ISendRecvRight (int nolayers, std::vector< double > & v) [inline]
Definition at line 76 of file mpi_tool.hpp.
                                                               {
       MakeItagCntCycle();
       int itag[2] = {itag_cnt++, itag_cnt++};
       int cnt = nolayers * no_one_layer_;
       auto [shift_send, shift_recv] = GetSendRecvPosition(nolayers);
       MPI_Request requests[2];
      // MPI_Status status[1];
       MPI_Isend(&v[shift_send[0]], cnt, MPI_DOUBLE, left_neighborhood,
                 itag[0], comm_world_, requests + 0);
       MPI_Irecv(&v[shift_recv[0]], cnt, MPI_DOUBLE, right_neighborhood,
                 itag[0], comm_world_, requests + 1);
      // MPI_Waitall(2, requests, status);
       return *this;
   }
IsMaster()
bool mpi::MpiTool::IsMaster () [inline]
Definition at line 164 of file mpi_tool.hpp.
{ return master_ == rank_; }
Referenced by CollectToMaster(), projection_method::CpuOpenMpMpi::CpuOpenMpMpi(), and projection_method::CpuOpenMpMpi::solve().
SendRecv()
MpiTool & mpi::MpiTool::SendRecv (int nolayers, std::vector< double > & v) [inline]
Definition at line 33 of file mpi_tool.hpp.
                                                          {
      auto [shift_send, shift_recv] = GetSendRecvPosition(nolayers);
      int cnt = nolayers * no_one_layer_;
      MakeItagCntCycle();
      int itag[2] = {itag_cnt++, itag_cnt++};
      MPI_Status status[2];
      // !`+`
      MPI_Send(&v[shift_send[0]], cnt, MPI_DOUBLE, left_neighborhood, itag[0],
               comm_world_);
      MPI_Recv(&v[shift_recv[0]], cnt, MPI_DOUBLE, right_neighborhood, itag[0],
               comm_world_, status);
      // !`-`
      MPI_Send(&v[shift_send[1]], cnt, MPI_DOUBLE, right_neighborhood, itag[1],
               comm_world_);
      MPI_Recv(&v[shift_recv[1]], cnt, MPI_DOUBLE, left_neighborhood, itag[1],
               comm_world_, status + 1);
      return *this;
    }
SendRecvLeft()
MpiTool & mpi::MpiTool::SendRecvLeft (int nolayers, std::vector< double > & v) [inline]
Definition at line 106 of file mpi_tool.hpp.
                                                             {
       MakeItagCntCycle();
       int itag[2] = {itag_cnt++, itag_cnt++};
       int cnt = nolayers * no_one_layer_;
       auto [shift_send, shift_recv] = GetSendRecvPosition(nolayers);
       MPI_Status status[1];
       MPI_Send(&v[shift_send[1]], cnt, MPI_DOUBLE, right_neighborhood,
                itag[1], comm_world_);
       MPI_Recv(&v[shift_recv[1]], cnt, MPI_DOUBLE, left_neighborhood,
                itag[1], comm_world_, status);
       return *this;
   }
SendRecvRight()
MpiTool & mpi::MpiTool::SendRecvRight (int nolayers, std::vector< double > & v) [inline]
Definition at line 119 of file mpi_tool.hpp.
                                                              {
       MakeItagCntCycle();
       int itag[2] = {itag_cnt++, itag_cnt++};
       int cnt = nolayers * no_one_layer_;
       auto [shift_send, shift_recv] = GetSendRecvPosition(nolayers);
       MPI_Status status[1];
       MPI_Send(&v[shift_send[0]], cnt, MPI_DOUBLE, left_neighborhood,
                itag[0], comm_world_);
       MPI_Recv(&v[shift_recv[0]], cnt, MPI_DOUBLE, right_neighborhood, itag[0],
                comm_world_, status);
       return *this;
   }
SetDomain()
void mpi::MpiTool::SetDomain (LocalDomain & domain) [inline]
Definition at line 24 of file mpi_tool.hpp.
                                       {
     domain_ = &domain;
   }
Referenced by projection_method::CpuOpenMpMpi::CpuOpenMpMpi().
The documentation for this class was generated from the following file:
cfd_mx/inc/mpi_tool/mpi_tool.hpp