solver::LinearSolverMpi< MatType > Class Template Reference
#include <linear_solver_mpi.hpp>
Public Member Functions
LinearSolverMpi ()
LinearSolverMpi (MatType &lhs_mat)
virtual ~LinearSolverMpi ()
void Construct (const MatType &lhs_mat)
void SetTolerance (double tolerance)
void SetMaxIters (int niters)
virtual std::tuple< int, double > solve (const std::vector< double > &rhs, std::vector< double > &x)=0
std::tuple< int, double > operator() (const std::vector< double > &rhs, std::vector< double > &x)
Protected Member Functions
double InnerProduct (const std::vector< double > &rhs, const std::vector< double > &x)
Protected Attributes
double tolerance_ {1e-5}
int iters_max_ {3000}
MatType lhs_mat_
mat::MpiVectorTool mpi_
Detailed Description
template<typename MatType>
class solver::LinearSolverMpi< MatType >
Definition at line 14 of file linear_solver_mpi.hpp.
Constructor & Destructor Documentation
LinearSolverMpi() [1/2]
template<typename MatType >
solver::LinearSolverMpi< MatType >::LinearSolverMpi () [inline]
Definition at line 16 of file linear_solver_mpi.hpp.
{}
LinearSolverMpi() [2/2]
template<typename MatType >
solver::LinearSolverMpi< MatType >::LinearSolverMpi (MatType & lhs_mat) [inline]
Definition at line 18 of file linear_solver_mpi.hpp.
{ Construct(lhs_mat); }
References solver::LinearSolverMpi< MatType >::Construct().
~LinearSolverMpi()
template<typename MatType >
virtual solver::LinearSolverMpi< MatType >::~LinearSolverMpi () [inline], [virtual]
Definition at line 20 of file linear_solver_mpi.hpp.
{}
Member Function Documentation
Construct()
template<typename MatType >
void solver::LinearSolverMpi< MatType >::Construct (const MatType & lhs_mat) [inline]
Definition at line 22 of file linear_solver_mpi.hpp.
                                         {
    // if (lhs_mat.mpi_.Empty()) {
    // throw std::runtime_error("out of dimensions!");
    // }
    lhs_mat_ = lhs_mat;
    mpi_ = lhs_mat.mpi_;
  }
References solver::LinearSolverMpi< MatType >::lhs_mat_, and solver::LinearSolverMpi< MatType >::mpi_.
Referenced by solver::LinearSolverMpi< MatType >::LinearSolverMpi().
InnerProduct()
template<typename MatType >
double solver::LinearSolverMpi< MatType >::InnerProduct (const std::vector< double > & rhs, const std::vector< double > & x) [inline], [protected]
Definition at line 48 of file linear_solver_mpi.hpp.
                                                  {
    return mpi_.InnerProduct(rhs, x);
  }
References mat::MpiVectorTool::InnerProduct(), and solver::LinearSolverMpi< MatType >::mpi_.
operator()()
template<typename MatType >
std::tuple< int, double > solver::LinearSolverMpi< MatType >::operator() (const std::vector< double > & rhs, std::vector< double > & x) [inline]
Definition at line 40 of file linear_solver_mpi.hpp.
                                                           {
    return solve(rhs, x);
  }
References solver::LinearSolverMpi< MatType >::solve().
SetMaxIters()
template<typename MatType >
void solver::LinearSolverMpi< MatType >::SetMaxIters (int niters) [inline]
Definition at line 32 of file linear_solver_mpi.hpp.
                               {
  }
SetTolerance()
template<typename MatType >
void solver::LinearSolverMpi< MatType >::SetTolerance (double tolerance) [inline]
Definition at line 30 of file linear_solver_mpi.hpp.
{ tolerance_ = tolerance; }
References solver::LinearSolverMpi< MatType >::tolerance_.
Referenced by projection_method::CpuOpenMpMpi::solve(), TEST(), and TEST().
solve()
template<typename MatType >
virtual std::tuple< int, double > solver::LinearSolverMpi< MatType >::solve (const std::vector< double > & rhs, std::vector< double > & x) [pure virtual]
Implemented in solver::BicgstabMpi< matrixT >, and solver::BicgstabMpi< MatType >.
Referenced by solver::LinearSolverMpi< MatType >::operator()().
Member Data Documentation
iters_max_
template<typename MatType >
int solver::LinearSolverMpi< MatType >::iters_max_ {3000} [protected]
Definition at line 47 of file linear_solver_mpi.hpp.
{3000};
lhs_mat_
template<typename MatType >
MatType solver::LinearSolverMpi< MatType >::lhs_mat_ [protected]
Definition at line 52 of file linear_solver_mpi.hpp.
Referenced by solver::LinearSolverMpi< MatType >::Construct().
mpi_
template<typename MatType >
mat::MpiVectorTool solver::LinearSolverMpi< MatType >::mpi_ [protected]
Definition at line 53 of file linear_solver_mpi.hpp.
Referenced by solver::LinearSolverMpi< MatType >::Construct(), and solver::LinearSolverMpi< MatType >::InnerProduct().
tolerance_
template<typename MatType >
double solver::LinearSolverMpi< MatType >::tolerance_ {1e-5} [protected]
Definition at line 46 of file linear_solver_mpi.hpp.
{1e-5};
Referenced by solver::LinearSolverMpi< MatType >::SetTolerance().
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/solver/mpi/linear_solver_mpi.hpp