mat::SparseMat< T > Class Template Reference
#include <sparse_mat.hpp>
Public Types
using CSR_type = std::tuple< std::vector< int >, std::vector< int >, std::vector< T > >
Public Member Functions
SparseMat (int rows, int cols)
SparseMat (int n)
SparseMat ()
virtual void Multiply (std::vector< T > &x, std::vector< T > &r)=0
void multiply_omp (std::vector< T > &x, std::vector< T > &r)
int row () const
int col () const
std::vector< T > Multiply (std::vector< T > &x)
std::vector< T > operator* (std::vector< T > &x)
void Construct (int rows, int cols)
void InitMpi (MPI_Comm comm_world, std::vector< int > beg, std::vector< int > end)
void InitMpi (MPI_Comm comm_world, int vec_size)
Public Attributes
MpiVectorTool mpi_
Detailed Description
template<typename T>
class mat::SparseMat< T >
Definition at line 7 of file sparse_mat.hpp.
Member Typedef Documentation
CSR_type
template<typename T >
using mat::SparseMat< T >::CSR_type = std::tuple< std::vector<int>, std::vector<int>, std::vector<T> >
Definition at line 9 of file sparse_mat.hpp.
Constructor & Destructor Documentation
SparseMat() [1/3]
template<typename T >
mat::SparseMat< T >::SparseMat (int rows, int cols) [inline]
Definition at line 13 of file sparse_mat.hpp.
{ Construct(rows, cols); }
References mat::SparseMat< T >::col(), and mat::SparseMat< T >::Construct().
SparseMat() [2/3]
template<typename T >
mat::SparseMat< T >::SparseMat (int n) [inline]
Definition at line 14 of file sparse_mat.hpp.
{ Construct(n, n); }
References mat::SparseMat< T >::col(), and mat::SparseMat< T >::Construct().
SparseMat() [3/3]
template<typename T >
mat::SparseMat< T >::SparseMat () [inline]
Definition at line 15 of file sparse_mat.hpp.
{}
Member Function Documentation
col()
template<typename T >
int mat::SparseMat< T >::col () const [inline]
Definition at line 21 of file sparse_mat.hpp.
{ return cols_; }
Referenced by mat::SparseMat< T >::Construct(), mat::EllMat< T >::EllMat(), mat::EllMat< T >::EllMat(), mat::SparseMat< T >::InitMpi(), mat::SparseMat< T >::InitMpi(), mat::EllMat< T >::Multiply(), mat::SparseMat< T >::multiply_omp(), mat::EllMat< T >::MultiplyMpi(), mat::EllMat< T >::resize(), mat::EllMat< T >::resize(), mat::SparseMat< T >::SparseMat(), mat::SparseMat< T >::SparseMat(), TEST(), TEST(), TEST(), and TEST().
Construct()
template<typename T >
void mat::SparseMat< T >::Construct (int rows, int cols) [inline]
Definition at line 33 of file sparse_mat.hpp.
                                     {
    if (rows < 0 || cols < 0) {
      throw std::invalid_argument("Matrix dimensions cannot be negative.");
    }
    rows_ = rows;
    cols_ = cols;
  }
References mat::SparseMat< T >::col().
Referenced by mat::CsrMat< T >::resize(), mat::EllMat< T >::resize(), mat::CsrMat< T >::resize(), mat::EllMat< T >::resize(), mat::SparseMat< T >::SparseMat(), and mat::SparseMat< T >::SparseMat().
InitMpi() [1/2]
template<typename T >
void mat::SparseMat< T >::InitMpi (MPI_Comm comm_world, int vec_size) [inline]
Definition at line 47 of file sparse_mat.hpp.
                                                  {
    mpi_.Init(comm_world, vec_size);
  }
References mat::SparseMat< T >::col(), mat::MpiVectorTool::Init(), and mat::SparseMat< T >::mpi_.
InitMpi() [2/2]
template<typename T >
void mat::SparseMat< T >::InitMpi (MPI_Comm comm_world, std::vector< int > beg, std::vector< int > end) [inline]
Definition at line 41 of file sparse_mat.hpp.
                                  {
    mpi_.Init(comm_world, beg, end);
  }
References mat::SparseMat< T >::col(), mat::MpiVectorTool::Init(), and mat::SparseMat< T >::mpi_.
Referenced by TEST(), TEST(), TEST(), and TEST().
Multiply() [1/2]
template<typename T >
std::vector< T > mat::SparseMat< T >::Multiply (std::vector< T > & x) [inline]
Definition at line 23 of file sparse_mat.hpp.
                                         {
    re_global_.resize(rows_);
    Multiply(x, re_global_);
    return re_global_;
  }
References mat::SparseMat< T >::Multiply().
Multiply() [2/2]
template<typename T >
virtual void mat::SparseMat< T >::Multiply (std::vector< T > & x, std::vector< T > & r) [pure virtual]
Implemented in mat::CsrMat< T >, and mat::EllMat< T >.
Referenced by mat::SparseMat< T >::Multiply(), mat::SparseMat< T >::multiply_omp(), and mat::SparseMat< T >::operator*().
multiply_omp()
template<typename T >
void mat::SparseMat< T >::multiply_omp (std::vector< T > & x, std::vector< T > & r) [inline]
Definition at line 18 of file sparse_mat.hpp.
{ Multiply(x, r); }
References mat::SparseMat< T >::col(), and mat::SparseMat< T >::Multiply().
operator*()
template<typename T >
std::vector< T > mat::SparseMat< T >::operator* (std::vector< T > & x) [inline]
Definition at line 29 of file sparse_mat.hpp.
                                          {
    return Multiply(x);
  }
References mat::SparseMat< T >::Multiply().
row()
template<typename T >
int mat::SparseMat< T >::row () const [inline]
Definition at line 20 of file sparse_mat.hpp.
{ return rows_; }
Referenced by mat::CsrMat< T >::Multiply(), and mat::EllMat< T >::Multiply().
Member Data Documentation
mpi_
template<typename T >
MpiVectorTool mat::SparseMat< T >::mpi_
Definition at line 52 of file sparse_mat.hpp.
Referenced by mat::SparseMat< T >::InitMpi(), mat::SparseMat< T >::InitMpi(), mat::CsrMat< T >::MultiplyMpi(), and mat::EllMat< T >::MultiplyMpi().
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/sparse_mat.hpp