solver::LinearSolver< matrixT > Class Template Reference
#include <linear_solver.hpp>
Public Member Functions
LinearSolver ()
LinearSolver (matrixT &lhs_mat)
virtual ~LinearSolver ()
void construct (const matrixT &lhs_mat)
virtual void SetTolerance (double tolerance)
void SetMaxIters (int niters)
virtual std::tuple< int, double > solve (const std::vector< double > &rhs, std::vector< double > &x)=0
std::tuple< int, double > operator() (const std::vector< double > &rhs, std::vector< double > &x)
Protected Member Functions
double InnerProduct (const std::vector< double > &rhs, const std::vector< double > &x)
Protected Attributes
matrixT lhs_mat_
double tolerance_ {1e-5}
int iters_max_ {3000}
Detailed Description
template<typename matrixT>
class solver::LinearSolver< matrixT >
Definition at line 13 of file linear_solver.hpp.
Constructor & Destructor Documentation
LinearSolver() [1/2]
template<typename matrixT >
solver::LinearSolver< matrixT >::LinearSolver () [inline]
Definition at line 15 of file linear_solver.hpp.
{}
LinearSolver() [2/2]
template<typename matrixT >
solver::LinearSolver< matrixT >::LinearSolver (matrixT & lhs_mat) [inline]
Definition at line 17 of file linear_solver.hpp.
{ construct(lhs_mat); }
References solver::LinearSolver< matrixT >::construct().
~LinearSolver()
template<typename matrixT >
virtual solver::LinearSolver< matrixT >::~LinearSolver () [inline], [virtual]
Definition at line 19 of file linear_solver.hpp.
{}
Member Function Documentation
construct()
template<typename matrixT >
void solver::LinearSolver< matrixT >::construct (const matrixT & lhs_mat) [inline]
Definition at line 21 of file linear_solver.hpp.
{ lhs_mat_ = lhs_mat; }
References solver::LinearSolver< matrixT >::lhs_mat_.
Referenced by solver::LinearSolver< matrixT >::LinearSolver().
InnerProduct()
template<typename matrixT >
double solver::LinearSolver< matrixT >::InnerProduct (const std::vector< double > & rhs, const std::vector< double > & x) [inline], [protected]
Definition at line 40 of file linear_solver.hpp.
                                                  {
    return math::InnerProduct(rhs, x);
  }
References math::InnerProduct().
operator()()
template<typename matrixT >
std::tuple< int, double > solver::LinearSolver< matrixT >::operator() (const std::vector< double > & rhs, std::vector< double > & x) [inline]
Definition at line 31 of file linear_solver.hpp.
                                                          {
    return solve(rhs, x);
  }
References solver::LinearSolver< matrixT >::solve().
SetMaxIters()
template<typename matrixT >
void solver::LinearSolver< matrixT >::SetMaxIters (int niters) [inline]
Definition at line 25 of file linear_solver.hpp.
{}
SetTolerance()
template<typename matrixT >
virtual void solver::LinearSolver< matrixT >::SetTolerance (double tolerance) [inline], [virtual]
Reimplemented in solver::BicgstabRestart< matrixT >, and solver::BicgstabRestart< MatType >.
Definition at line 23 of file linear_solver.hpp.
{ tolerance_ = tolerance; }
References solver::LinearSolver< matrixT >::tolerance_.
Referenced by TEST(), and TEST().
solve()
template<typename matrixT >
virtual std::tuple< int, double > solver::LinearSolver< matrixT >::solve (const std::vector< double > & rhs, std::vector< double > & x) [pure virtual]
Implemented in solver::Bicgstab< MatType >, solver::BicgstabRestart< matrixT >, and solver::BicgstabRestart< MatType >.
Referenced by solver::LinearSolver< matrixT >::operator()().
Member Data Documentation
iters_max_
template<typename matrixT >
int solver::LinearSolver< matrixT >::iters_max_ {3000} [protected]
Definition at line 39 of file linear_solver.hpp.
{3000};
Referenced by solver::BicgstabRestart< matrixT >::solve().
lhs_mat_
template<typename matrixT >
matrixT solver::LinearSolver< matrixT >::lhs_mat_ [protected]
Definition at line 37 of file linear_solver.hpp.
Referenced by solver::LinearSolver< matrixT >::construct(), solver::BicgstabRestart< matrixT >::init(), and solver::BicgstabRestart< matrixT >::solve().
tolerance_
template<typename matrixT >
double solver::LinearSolver< matrixT >::tolerance_ {1e-5} [protected]
Definition at line 38 of file linear_solver.hpp.
{1e-5};
Referenced by solver::LinearSolver< matrixT >::SetTolerance(), solver::BicgstabRestart< matrixT >::SetTolerance(), and solver::BicgstabRestart< matrixT >::solve().
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/solver/linear_solver.hpp