solver::Bicgstab< MatType > Class Template Reference
#include <bicgstab.hpp>
Public Member Functions
Bicgstab ()
Bicgstab (MatType &lhs_mat)
virtual ~Bicgstab ()
void Init (const MatType &lhs_mat)
std::tuple< int, double > solve (const std::vector< double > &rhs, std::vector< double > &x) override
Public Member Functions inherited from solver::LinearSolver< MatType >
LinearSolver ()
LinearSolver (MatType &lhs_mat)
virtual ~LinearSolver ()
void construct (const MatType &lhs_mat)
virtual void SetTolerance (double tolerance)
void SetMaxIters (int niters)
std::tuple< int, double > operator() (const std::vector< double > &rhs, std::vector< double > &x)
Additional Inherited Members
Protected Member Functions inherited from solver::LinearSolver< MatType >
double InnerProduct (const std::vector< double > &rhs, const std::vector< double > &x)
Protected Attributes inherited from solver::LinearSolver< MatType >
MatType lhs_mat_
double tolerance_
int iters_max_
Detailed Description
template<typename MatType>
class solver::Bicgstab< MatType >
Definition at line 13 of file bicgstab.hpp.
Constructor & Destructor Documentation
Bicgstab() [1/2]
template<typename MatType >
solver::Bicgstab< MatType >::Bicgstab () [inline]
Definition at line 15 of file bicgstab.hpp.
{}
Bicgstab() [2/2]
template<typename MatType >
solver::Bicgstab< MatType >::Bicgstab (MatType & lhs_mat) [inline]
Definition at line 17 of file bicgstab.hpp.
: LinearSolver<MatType>(lhs_mat) { Init(lhs_mat); }
References solver::Bicgstab< MatType >::Init().
~Bicgstab()
template<typename MatType >
virtual solver::Bicgstab< MatType >::~Bicgstab () [inline], [virtual]
Definition at line 19 of file bicgstab.hpp.
{}
Member Function Documentation
Init()
template<typename MatType >
void solver::Bicgstab< MatType >::Init (const MatType & lhs_mat) [inline]
Definition at line 21 of file bicgstab.hpp.
                                           {
    this->lhs_mat_ = lhs_mat;
    length_ = lhs_mat.row();
    p_.resize(length_);
    r_.resize(length_);
    r2_.resize(length_);
    v_.resize(length_);
    ss_.resize(length_);
    t_.resize(length_);
  }
References solver::LinearSolver< MatType >::lhs_mat_.
Referenced by solver::Bicgstab< MatType >::Bicgstab().
solve()
template<typename MatType >
std::tuple< int, double > solver::Bicgstab< MatType >::solve (const std::vector< double > & rhs, std::vector< double > & x) [inline], [override], [virtual]
Implements solver::LinearSolver< MatType >.
Definition at line 32 of file bicgstab.hpp.
                                                                   {
    int iters{0};
    double norm{0};
    double norm_rhs = math::L2Norm(rhs);
    this->lhs_mat_.Multiply(x, p_);
    for (int i = 0; i < length_; ++i) r_[i] = rhs[i] - p_[i];
    for (int i = 0; i < length_; ++i) r2_[i] = r_[i];
    rho1_ = 1;
    alpha_ = 1;
    omega_ = 1;
    for (int i = 0; i < length_; ++i) {
      v_[i] = 0.0;
    }
    for (int i = 0; i < length_; ++i) {
      p_[i] = 0.0;
    }
    norm = math::L2Norm(r_) / norm_rhs;
    iters = 0;
    while (norm > this->tolerance_ && iters < this->iters_max_) {
      ++iters;
      rho2_ = math::InnerProduct(r2_, r_);
      beta_ = (rho2_ / rho1_) * (alpha_ / omega_);
      for (int i = 0; i < length_; ++i)
        p_[i] = r_[i] + beta_ * (p_[i] - omega_ * v_[i]);
      this->lhs_mat_.Multiply(p_, v_);
      alpha_ = rho2_ / math::InnerProduct(r2_, v_);
      for (int i = 0; i < length_; ++i) ss_[i] = r_[i] - alpha_ * v_[i];
      this->lhs_mat_.Multiply(ss_, t_);
      omega_ = math::InnerProduct(t_, ss_) / math::InnerProduct(t_, t_);
      for (int i = 0; i < length_; ++i)
        x[i] += alpha_ * p_[i] + omega_ * ss_[i];
      for (int i = 0; i < length_; ++i) r_[i] = ss_[i] - omega_ * t_[i];
      rho1_ = rho2_;
      norm = 0;
      norm = math::InnerProduct(r_, r_);
      norm = sqrt(norm) / norm_rhs;
    }
    return std::make_tuple(iters, norm);
  }
References math::InnerProduct(), solver::LinearSolver< MatType >::iters_max_, math::L2Norm(), solver::LinearSolver< MatType >::lhs_mat_, and solver::LinearSolver< MatType >::tolerance_.
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/solver/bicgstab.hpp