mat::EllMat< T > Class Template Reference
#include <ell_sparse_mat.hpp>
Public Member Functions
EllMat ()
EllMat (int rows, int cols, int nnz)
EllMat (int n, int nnz)
virtual ~EllMat ()
void resize (int rows, int cols, int nnz)
void resize (int n, int nnz)
void Multiply (std::vector< T > &x, std::vector< T > &r) override
void MultiplyMpi (std::vector< T > &x, std::vector< T > &r)
int MaxRow ()
void Show ()
bool analyse ()
EllMat< T > & Set (int row, int col, T val)
EllMat< T > & Set (typename SparseMat< T >::CSR_type c)
Public Member Functions inherited from mat::SparseMat< T >
SparseMat (int rows, int cols)
SparseMat (int n)
SparseMat ()
void multiply_omp (std::vector< T > &x, std::vector< T > &r)
int row () const
int col () const
std::vector< T > Multiply (std::vector< T > &x)
std::vector< T > operator* (std::vector< T > &x)
void Construct (int rows, int cols)
void InitMpi (MPI_Comm comm_world, std::vector< int > beg, std::vector< int > end)
void InitMpi (MPI_Comm comm_world, int vec_size)
Friends
template<typename X >
std::ostream & operator<< (std::ostream &os, const EllMat< X > &mat)
Additional Inherited Members
Public Types inherited from mat::SparseMat< T >
using CSR_type = std::tuple< std::vector< int >, std::vector< int >, std::vector< T > >
Public Attributes inherited from mat::SparseMat< T >
MpiVectorTool mpi_
Detailed Description
template<typename T>
class mat::EllMat< T >
Definition at line 17 of file ell_sparse_mat.hpp.
Constructor & Destructor Documentation
EllMat() [1/3]
template<typename T >
mat::EllMat< T >::EllMat () [inline]
Definition at line 20 of file ell_sparse_mat.hpp.
: SparseMat<T>() {}
EllMat() [2/3]
template<typename T >
mat::EllMat< T >::EllMat (int rows, int cols, int nnz) [inline]
Definition at line 22 of file ell_sparse_mat.hpp.
                                        : SparseMat<T>(rows, cols) {
      SelfConstruct(nnz);
    }
References mat::SparseMat< T >::col().
EllMat() [3/3]
template<typename T >
mat::EllMat< T >::EllMat (int n, int nnz) [inline]
Definition at line 25 of file ell_sparse_mat.hpp.
: SparseMat<T>(n, n) { SelfConstruct(nnz); }
References mat::SparseMat< T >::col().
~EllMat()
template<typename T >
virtual mat::EllMat< T >::~EllMat () [inline], [virtual]
Definition at line 27 of file ell_sparse_mat.hpp.
{ Destruct(); };
Member Function Documentation
analyse()
template<typename T >
bool mat::EllMat< T >::analyse (void) [inline]
Definition at line 194 of file ell_sparse_mat.hpp.
                                     {
    // -----------------------------------
    std::vector<int> a(no_no_zero_ + 1, 0);
    for (auto v : curr_idx_size) {
      ++a[v];
    }
    // -----------------------------------
    int i{0};
    // -----------------------------------
    for (auto v : a) {
      std::cout << "i=" << i++ << ", " << v << "\n";
    }
    // -----------------------------------
    return true;
  }
MaxRow()
template<typename T >
int mat::EllMat< T >::MaxRow () [inline]
Definition at line 63 of file ell_sparse_mat.hpp.
{ return no_no_zero_; }
Multiply()
template<typename T >
void mat::EllMat< T >::Multiply (std::vector< T > & x, std::vector< T > & r) [inline], [override], [virtual]
Implements mat::SparseMat< T >.
Definition at line 39 of file ell_sparse_mat.hpp.
                                                               {
#pragma omp parallel for
      for (int i = 0; i < this->row(); ++i) {
        const int pt = i * no_no_zero_;
        r[i] = T();
        // for(int j = 0; j < curr_idx_size[i];++j){
        for (int j = 0; j < no_no_zero_; ++j) {
          r[i] += val_[pt + j] * x[idx_[pt + j]];
        }
      }
    }
References mat::SparseMat< T >::col(), and mat::SparseMat< T >::row().
MultiplyMpi()
template<typename T >
void mat::EllMat< T >::MultiplyMpi (std::vector< T > & x, std::vector< T > & r) [inline]
Definition at line 51 of file ell_sparse_mat.hpp.
                                                         {
      this->mpi_.Allocate(x);
      for (auto i = this->mpi_.beg(); i < this->mpi_.end(); ++i) {
        const int pt = i * no_no_zero_;
        r[i] = T();
        for (int j = 0; j < no_no_zero_; ++j) {
          r[i] += val_[pt + j] * x[idx_[pt + j]];
        }
      }
    }
References mat::MpiVectorTool::Allocate(), mat::MpiVectorTool::beg(), mat::SparseMat< T >::col(), mat::MpiVectorTool::end(), and mat::SparseMat< T >::mpi_.
resize() [1/2]
template<typename T >
void mat::EllMat< T >::resize (int n, int nnz) [inline]
Definition at line 34 of file ell_sparse_mat.hpp.
                                {
      this->Construct(n, n);
      SelfConstruct(nnz);
     }
References mat::SparseMat< T >::col(), and mat::SparseMat< T >::Construct().
resize() [2/2]
template<typename T >
void mat::EllMat< T >::resize (int rows, int cols, int nnz) [inline]
Definition at line 29 of file ell_sparse_mat.hpp.
                                             {
      this->Construct(rows, cols);
      SelfConstruct(nnz);
    }
References mat::SparseMat< T >::col(), and mat::SparseMat< T >::Construct().
Set() [1/2]
template<typename T >
EllMat< T > & mat::EllMat< T >::Set (int row, int col, T val) [inline]
Definition at line 135 of file ell_sparse_mat.hpp.
                                                          {
    if (row < 0 || col < 0) {
      throw std::invalid_argument("Matrix dimensions cannot be negative.");
    }
    if (col >= this->col()) {
      std::cout << col << " >= " << this->col() << std::endl;
      throw std::invalid_argument("colIdx >= no_no_zero_ ");
    }
    if (row >= this->row()) throw std::invalid_argument("row >= this->row()");
    const int pt = row * no_no_zero_;
    if (val == T()) {
      // bool is_new_one = true;
      for (int i = 0; i < curr_idx_size[row]; ++i) {
        if (col == idx_[pt + i]) {
          // is_new_one = false; --> remove
          for (int j = i; j < curr_idx_size[row]; ++j) {
            idx_[pt + j] = idx_[pt + j + 1];
            val_[pt + j] = idx_[pt + j + 1];
          }
          idx_[pt + curr_idx_size[row]] = init_idx_;
          val_[pt + curr_idx_size[row]] = T();
          curr_idx_size[row]--;
          return *this;
        }
      }
      return *this;
    } else {
      bool is_new_one = true;
      for (int i = 0; i < curr_idx_size[row]; ++i) {
        if (col == idx_[pt + i]) {
          is_new_one = false;
          idx_[pt + i] = col;
          val_[pt + i] = val;
          return *this;
        }
      }
      if (is_new_one) {
        idx_[pt + curr_idx_size[row]] = col;
        val_[pt + curr_idx_size[row]] = val;
        curr_idx_size[row]++;
      }
      if (curr_idx_size[row] > no_no_zero_) {
        throw std::invalid_argument(
            "[ELL0::Set] -> curr_idx_size[row] >no_no_zero_");
      }
      return *this;
    }
  }
Referenced by TEST(), and TEST().
Set() [2/2]
template<typename T >
EllMat< T > & mat::EllMat< T >::Set (typename SparseMat< T >::CSR_type c) [inline]
Definition at line 111 of file ell_sparse_mat.hpp.
                                                                  {
    auto [prt, idx, val] = c;
    // ! We assume that your mat is a n by n mat for our convenient.
    this->Construct(prt.size() - 1, prt.size() - 1);
    no_no_zero_ = 0;
    // find max index
    for (int row = 0; row < this->row(); ++row) {
      no_no_zero_ = std::max(prt[row + 1] - prt[row], no_no_zero_);
    }
    SelfConstruct(no_no_zero_);
 
    for (int row = 0; row < this->row(); ++row) {
      for (int j = prt[row]; j < prt[row + 1]; ++j) {
        Set(row, idx[j], val[j]);
      }
    }
    return *this;
  }
Show()
template<typename T >
void mat::EllMat< T >::Show () [inline]
Definition at line 211 of file ell_sparse_mat.hpp.
                              {
    std::cout << " |val";
    for (int i = 0; i < no_no_zero_; ++i) {
      std::cout << std::setw(4) << "";
    }
    std::cout << " |Idx\n";
    for (int i = 0; i < this->row(); ++i) {
      // ----------------------------------------
      std::cout << std::setw(3) << i << "|";
      // ----------------------------------------
      for (int j = 0; j < no_no_zero_; ++j) {
        std::cout << std::setw(4) << val_[i * no_no_zero_ + j] << " ";
      }
      // ----------------------------------------
      std::cout << "|";
      // ----------------------------------------
      for (int j = 0; j < no_no_zero_; ++j) {
        std::cout << std::setw(4) << idx_[i * no_no_zero_ + j] << " ";
      }
      // ----------------------------------------
      std::cout << std::endl;
    }
  }
Friends And Related Symbol Documentation
operator<<
template<typename T >
template<typename X >
std::ostream & operator<< (std::ostream & os, const EllMat< X > & mat) [friend]
The documentation for this class was generated from the following file:
cfd_mx/inc/matrix/ell_sparse_mat.hpp