TimeVarianceAuthority Class Reference
#include <time_variance_authority.hpp>
Public Member Functions
auto GetTime ()
auto SetTerminalTime (double terminal_time)
TimeVarianceAuthority & SetDt (double t)
TimeVarianceAuthority & SetWritingDt (double writing_dt)
double GetPercentageOfWriting ()
auto GetFileNo ()
bool IsWritingTime ()
void AddLoop ()
bool IsLoopFinish ()
TimeVarianceAuthority & SetTime (double t)
auto GetDt ()
auto GetLoop ()
Detailed Description
Definition at line 5 of file time_variance_authority.hpp.
Member Function Documentation
AddLoop()
void TimeVarianceAuthority::AddLoop () [inline]
Definition at line 36 of file time_variance_authority.hpp.
                 {
    time_ += dt_;
    loop_++;
    dt_ = dt_next_;
  }
Referenced by projection_method::CpuOpenMp::solve(), and projection_method::CpuOpenMpMpi::solve().
GetDt()
auto TimeVarianceAuthority::GetDt () [inline]
Definition at line 51 of file time_variance_authority.hpp.
{ return dt_;}
Referenced by CalConvectionAndDiffusion().
GetFileNo()
auto TimeVarianceAuthority::GetFileNo () [inline]
Definition at line 25 of file time_variance_authority.hpp.
{ return cnt_file_; }
Referenced by WriteQfile().
GetLoop()
auto TimeVarianceAuthority::GetLoop () [inline]
Definition at line 52 of file time_variance_authority.hpp.
{return loop_;}
GetPercentageOfWriting()
double TimeVarianceAuthority::GetPercentageOfWriting () [inline]
Definition at line 24 of file time_variance_authority.hpp.
{ return (time_ / writing_dt_); }
GetTime()
auto TimeVarianceAuthority::GetTime () [inline]
Definition at line 7 of file time_variance_authority.hpp.
{ return time_; }
Referenced by WriteQfile().
IsLoopFinish()
bool TimeVarianceAuthority::IsLoopFinish () [inline]
Definition at line 42 of file time_variance_authority.hpp.
                      {
    return time_ > terminal_time_+dt_;
  }
Referenced by projection_method::CpuOpenMp::solve(), and projection_method::CpuOpenMpMpi::solve().
IsWritingTime()
bool TimeVarianceAuthority::IsWritingTime () [inline]
Definition at line 26 of file time_variance_authority.hpp.
                       {
    auto time_file_next = writing_time_ + writing_dt_;
    if (time_ >= time_file_next) {
      cnt_file_++;
      writing_time_ += writing_dt_;
      return true;
    } else {
      return false;
    }
  }
SetDt()
TimeVarianceAuthority & TimeVarianceAuthority::SetDt (double t) [inline]
Definition at line 13 of file time_variance_authority.hpp.
                                         {
    dt_ = t;
    IniTimeRecoding();
    return *this;
  }
Referenced by TEST(), and TEST().
SetTerminalTime()
auto TimeVarianceAuthority::SetTerminalTime (double terminal_time) [inline]
Definition at line 8 of file time_variance_authority.hpp.
                                             {
    terminal_time_ = terminal_time;
    loop_max_ = terminal_time_ / dt_;
  }
Referenced by TEST(), and TEST().
SetTime()
TimeVarianceAuthority & TimeVarianceAuthority::SetTime (double t) [inline]
Definition at line 46 of file time_variance_authority.hpp.
                                           {
    time_ = t;
    return *this;
  }
SetWritingDt()
TimeVarianceAuthority & TimeVarianceAuthority::SetWritingDt (double writing_dt) [inline]
Definition at line 19 of file time_variance_authority.hpp.
                                                         {
    writing_dt_ = writing_dt;
    return *this;
  }
Referenced by TEST(), and TEST().
The documentation for this class was generated from the following file:
cfd_mx/inc/backend/time_variance_authority.hpp