projection_method::CpuOpenMpMpi Class Reference
#include <test_run_mpi.hpp>
Public Member Functions
~CpuOpenMpMpi ()
CpuOpenMpMpi (Simulation &simu, StructuredGrid &grid)
void solve ()
~CpuOpenMpMpi ()
CpuOpenMpMpi (Simulation &simu, StructuredGrid &grid)
void solve ()
Detailed Description
Definition at line 15 of file test_run_mpi.hpp.
Constructor & Destructor Documentation
~CpuOpenMpMpi() [1/2]
projection_method::CpuOpenMpMpi::~CpuOpenMpMpi () [inline]
Definition at line 20 of file test_run_mpi.hpp.
{ MPI_Finalize(); }
CpuOpenMpMpi() [1/2]
projection_method::CpuOpenMpMpi::CpuOpenMpMpi (Simulation & simu, StructuredGrid & grid) [inline]
Definition at line 21 of file test_run_mpi.hpp.
        : simu_(simu),
          grid_(&grid),
          vel_(StaggeredVelocity(grid)),
          intermediate_vel_(StaggeredVelocity(grid)),
          mpi_tool_(mpi::MpiTool(simu.GetArgc(), simu.GetArgv(), grid)),
          dfib_(ImmersedBoundary(grid)),
          pressure_mat_(PressureMat(grid)),
          local_domain_(LocalDomain(grid)),
          global_domain_(LocalDomain(grid)),
          pressure_(Pressure(grid))
    {
      vel_.FillVel(simu.ini_condition.u, simu.ini_condition.v, simu.ini_condition.w);
      if (mpi_tool_.IsMaster()) {
        CreatOutputFile();
        PrintIsOpenmpExist();
      }
      std::vector<int> grid_size{grid.nx, grid.ny, grid.nz};
      global_domain_.Init({1, 1, 1}, {0, 0, 0});
      std::cout << mpi::GetRank();
      local_domain_.Init({mpi::GetSize(), 1, 1}, {mpi::GetRank(), 0, 0});
      mpi_tool_.SetDomain(local_domain_);
      simu.pid = mpi_tool_.GetRank();
      if (mpi_tool_.IsMaster()) {
        csv::WriteCsvFile("Information/grid.csv", *grid_);
        plot3d::write_xfile(grid);
      }
      UpdateAllVelocityOnBoundary(global_domain_, vel_, pressure_, grid);
      CopyVelocityOnBoundary(global_domain_, vel_, intermediate_vel_, grid);
      auto [start, end] = local_domain_.GetOneDimStartEnd();
      pressure_mat_.mat_a.InitMpi(mpi_tool_.GetCommWorld(), start, end);
    }
References CopyVelocityOnBoundary(), CreatOutputFile(), StaggeredVelocity::FillVel(), mpi::MpiTool::GetCommWorld(), LocalDomain::GetOneDimStartEnd(), mpi::GetRank(), mpi::MpiTool::GetRank(), mpi::GetSize(), Simulation::ini_condition, LocalDomain::Init(), mpi::MpiTool::IsMaster(), PressureMat::mat_a, StructuredGrid::nx, StructuredGrid::ny, StructuredGrid::nz, Simulation::pid, PrintIsOpenmpExist(), mpi::MpiTool::SetDomain(), IniCondition::u, UpdateAllVelocityOnBoundary(), IniCondition::v, IniCondition::w, plot3d::write_xfile(), and csv::WriteCsvFile().
~CpuOpenMpMpi() [2/2]
projection_method::CpuOpenMpMpi::~CpuOpenMpMpi () [inline]
Definition at line 19 of file run_cpu_mpi.hpp.
{ MPI_Finalize(); }
CpuOpenMpMpi() [2/2]
projection_method::CpuOpenMpMpi::CpuOpenMpMpi (Simulation & simu, StructuredGrid & grid) [inline]
Definition at line 20 of file run_cpu_mpi.hpp.
        : simu_(simu),
          grid_(&grid),
          vel_(StaggeredVelocity(grid)),
          intermediate_vel_(StaggeredVelocity(grid)),
          mpi_tool_(mpi::MpiTool(simu.GetArgc(), simu.GetArgv(), grid)),
          dfib_(ImmersedBoundary(grid)),
          pressure_mat_(PressureMat(grid)),
          local_domain_(LocalDomain(grid)),
          global_domain_(LocalDomain(grid)),
          pressure_(Pressure(grid))
    {
      vel_.FillVel(simu.ini_condition.u, simu.ini_condition.v, simu.ini_condition.w);
      if (mpi_tool_.IsMaster()) {
        CreatOutputFile();
        PrintIsOpenmpExist();
      }
      std::vector<int> grid_size{grid.nx, grid.ny, grid.nz};
      global_domain_.Init({1, 1, 1}, {0, 0, 0});
      std::cout << mpi::GetRank();
      local_domain_.Init({mpi::GetSize(), 1, 1}, {mpi::GetRank(), 0, 0});
      mpi_tool_.SetDomain(local_domain_);
      simu.pid = mpi_tool_.GetRank();
      if (mpi_tool_.IsMaster()) {
        csv::WriteCsvFile("Information/grid.csv", *grid_);
        plot3d::write_xfile(grid);
      }
      UpdateAllVelocityOnBoundary(global_domain_, vel_, pressure_, grid);
      CopyVelocityOnBoundary(global_domain_, vel_, intermediate_vel_, grid);
      auto [start, end] = local_domain_.GetOneDimStartEnd();
      pressure_mat_.mat_a.InitMpi(mpi_tool_.GetCommWorld(), start, end);
    }
References CopyVelocityOnBoundary(), CreatOutputFile(), StaggeredVelocity::FillVel(), mpi::MpiTool::GetCommWorld(), LocalDomain::GetOneDimStartEnd(), mpi::GetRank(), mpi::MpiTool::GetRank(), mpi::GetSize(), Simulation::ini_condition, LocalDomain::Init(), mpi::MpiTool::IsMaster(), PressureMat::mat_a, StructuredGrid::nx, StructuredGrid::ny, StructuredGrid::nz, Simulation::pid, PrintIsOpenmpExist(), mpi::MpiTool::SetDomain(), IniCondition::u, UpdateAllVelocityOnBoundary(), IniCondition::v, IniCondition::w, plot3d::write_xfile(), and csv::WriteCsvFile().
Member Function Documentation
solve() [1/2]
void projection_method::CpuOpenMpMpi::solve () [inline]
Definition at line 54 of file run_cpu_mpi.hpp.
                 {
      pressure_solver_ = SolverType(pressure_mat_.mat_a);
      pressure_solver_.SetTolerance(simu_.poisson_criteria);
      CreatEta();
      if (mpi_tool_.IsMaster()) {
      WriteQfile(dfib_, simu_, pressure_, vel_, *grid_);
      }
      for (; !simu_.tva.IsLoopFinish(); simu_.tva.AddLoop()) {
        CalProjectionMethod();
      }
      mpi_tool_.Barrier();
    }
References TimeVarianceAuthority::AddLoop(), mpi::MpiTool::Barrier(), TimeVarianceAuthority::IsLoopFinish(), mpi::MpiTool::IsMaster(), PressureMat::mat_a, Simulation::poisson_criteria, solver::LinearSolverMpi< MatType >::SetTolerance(), Simulation::tva, and WriteQfile().
solve() [2/2]
void projection_method::CpuOpenMpMpi::solve () [inline]
Definition at line 55 of file test_run_mpi.hpp.
                 {
      pressure_solver_ = SolverType(pressure_mat_.mat_a);
      pressure_solver_.SetTolerance(simu_.poisson_criteria);
      CreatEta();
      if (mpi_tool_.IsMaster()) {
      WriteQfile(dfib_, simu_, pressure_, vel_, *grid_);
      }
      for (; !simu_.tva.IsLoopFinish(); simu_.tva.AddLoop()) {
        CalProjectionMethod();
      }
      mpi_tool_.Barrier();
    }
References TimeVarianceAuthority::AddLoop(), mpi::MpiTool::Barrier(), TimeVarianceAuthority::IsLoopFinish(), mpi::MpiTool::IsMaster(), PressureMat::mat_a, Simulation::poisson_criteria, solver::LinearSolverMpi< MatType >::SetTolerance(), Simulation::tva, and WriteQfile().
The documentation for this class was generated from the following files:
tests/run/test_run_mpi.hpp
cfd_mx/inc/run/run_cpu_mpi.hpp