PhysicalVal Class Reference
#include <physical_variables.hpp>
Public Member Functions
PhysicalVal (StructuredGrid &grid)
Protected Member Functions
template<typename T >
size_t icelCal (T i, T j, T k) const
template<typename T >
size_t icel (T i, T j, T k) const
void Fill (std::vector< double > &v, double val)
Protected Attributes
StructuredGrid * grid_
Detailed Description
Definition at line 8 of file physical_variables.hpp.
Constructor & Destructor Documentation
PhysicalVal()
PhysicalVal::PhysicalVal (StructuredGrid & grid) [inline]
Definition at line 11 of file physical_variables.hpp.
: grid_(&grid){}
Member Function Documentation
Fill()
void PhysicalVal::Fill (std::vector< double > & v, double val) [inline], [protected]
Definition at line 23 of file physical_variables.hpp.
                                                     {
    #pragma omp for schedule(static)
    for (size_t i = 0; i < v.size(); ++i) {
      v[i] = val;
    }
  }
Referenced by StaggeredVelocity::FillVel().
icel()
template<typename T >
size_t PhysicalVal::icel (T i, T j, T k) const [inline], [protected]
Definition at line 32 of file physical_variables.hpp.
                                            {
    return grid_->icel(i, j, k);
}
References grid_, and StructuredGrid::icel().
Referenced by ImmersedBoundary::Eta(), ImmersedBoundary::Eta(), Pressure::operator()(), Pressure::operator()(), StaggeredVelocity::U(), StaggeredVelocity::U(), StaggeredVelocity::V(), StaggeredVelocity::V(), StaggeredVelocity::W(), and StaggeredVelocity::W().
icelCal()
template<typename T >
size_t PhysicalVal::icelCal (T i, T j, T k) const [inline], [protected]
Definition at line 38 of file physical_variables.hpp.
                                               {
    return grid_->icelCal(i, j, k);
}
References grid_, and StructuredGrid::icelCal().
Referenced by ImmersedBoundary::Fx(), ImmersedBoundary::Fx(), ImmersedBoundary::Fy(), ImmersedBoundary::Fy(), ImmersedBoundary::Fz(), ImmersedBoundary::Fz(), and StaggeredVelocity::VisEff().
Member Data Documentation
grid_
StructuredGrid* PhysicalVal::grid_ [protected]
Definition at line 13 of file physical_variables.hpp.
Referenced by StaggeredVelocity::GetGrid(), icel(), icelCal(), and ImmersedBoundary::ImmersedBoundary().
The documentation for this class was generated from the following file:
cfd_mx/inc/backend/physical_variables.hpp