tests/validation_tool/l2norm_validation.hpp File Reference
Functions
template<typename T >
auto L2Norm (std::vector< T > &a, std::vector< T > &b)
Function Documentation
L2Norm()
template<typename T >
auto L2Norm (std::vector< T > & a, std::vector< T > & b)
Definition at line 4 of file l2norm_validation.hpp.
                                              {
  T sum = 0;
  for (int i = 0; i < a.size(); i++) {
    sum += pow(a[i] - b[i], 2);
  }
  return sqrt(sum);
}
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().