tests/matrix/mpi_openmp_matrix_test.cpp File Reference
#include <gtest/gtest.h>
#include "../../cfd_mx/inc/matrix/csr_sparse_mat.hpp"
#include "../../cfd_mx/inc/matrix/ell_sparse_mat.hpp"
#include "../../cfd_mx/inc/matrix/solver/bicgstab.hpp"
#include "../../cfd_mx/inc/matrix/solver/bicgstab_restart.hpp"
#include "../../cfd_mx/inc/matrix/solver/mpi/bicgstab_mpi.hpp"
#include "../../cfd_mx/inc/matrix/solver/mpi/bicgstab_restart_mpi.hpp"
#include "../../cfd_mx/inc/mpi_tool/mpi_complex.hpp"
#include "../../cfd_mx/inc/mpi_tool/mpi_getter.hpp"
#include "../../cfd_mx/inc/mpi_tool/mpi_tool.hpp"
#include "../validation_tool/l2norm_validation.hpp"
#include "io_2d_plot3d.hpp"
#include "poisson.hpp"
Functions
TEST (csr_mpi, BicgstabRestart)
TEST (csr_mpi, Bicgstab)
TEST (EllMat, BicgstabRestartMpi)
TEST (EllMat, Bicgstab)
int main (int argc, char **argv)
Variables
mpi::MpiComplex mpi_complex_
HeatConduction heat_conduction (100)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 109 of file mpi_openmp_matrix_test.cpp.
                                {
  mpi_complex_ = mpi::MpiComplex(argc, argv);
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
References mpi_complex_.
TEST() [1/4]
TEST (csr_mpi , Bicgstab)
Definition at line 43 of file mpi_openmp_matrix_test.cpp.
                        {
  mat::CsrMat<double> matA;
  matA.Set(heat_conduction.GetCsr());
  matA.InitMpi(mpi_complex_.GetCommWorld(), matA.col());
  solver::BicgstabMpi<mat::CsrMat<double>> solverA(matA);
  mat::CsrMat<double> matB;
  matB.Set(heat_conduction.GetCsr());
  solver::Bicgstab<mat::CsrMat<double>> solverB(matB);
  solverA.SetTolerance(1.0e-9);
  solverB.SetTolerance(1.0e-9);
  for (int i = 0; i < 100; i++) {
    auto resultA = heat_conduction.x;
    auto resultB = heat_conduction.x;
    solverA(heat_conduction.rhs, resultA);
    solverB(heat_conduction.rhs, resultB);
    EXPECT_TRUE(L2Norm(resultA, resultB) < 1.0e-8);
  }
}
References mat::SparseMat< T >::col(), HeatConduction::GetCsr(), heat_conduction, mat::SparseMat< T >::InitMpi(), L2Norm(), mpi_complex_, HeatConduction::rhs, mat::CsrMat< T >::Set(), solver::LinearSolver< matrixT >::SetTolerance(), solver::LinearSolverMpi< MatType >::SetTolerance(), and HeatConduction::x.
TEST() [2/4]
TEST (csr_mpi , BicgstabRestart)
Definition at line 20 of file mpi_openmp_matrix_test.cpp.
                               {
  mat::CsrMat<double> matA;
  matA.Set(heat_conduction.GetCsr());
  matA.InitMpi(mpi_complex_.GetCommWorld(), matA.col());
  solver::BicgstabRestartMpi<mat::CsrMat<double>> solverA(matA);
  mat::CsrMat<double> matB;
  matB.Set(heat_conduction.GetCsr());
  solver::BicgstabRestart<mat::CsrMat<double>> solverB(matB);
  solverA.SetTolerance(1.0e-9);
  solverB.SetTolerance(1.0e-9);
  for (int i = 0; i < 100; i++) {
    auto resultA = heat_conduction.x;
    auto resultB = heat_conduction.x;
    solverA(heat_conduction.rhs, resultA);
    solverB(heat_conduction.rhs, resultB);
    EXPECT_TRUE(L2Norm(resultA, resultB) < 1.0e-8);
  }
}
References mat::SparseMat< T >::col(), HeatConduction::GetCsr(), heat_conduction, mat::SparseMat< T >::InitMpi(), L2Norm(), mpi_complex_, HeatConduction::rhs, mat::CsrMat< T >::Set(), solver::BicgstabRestartMpi< matrixT >::SetTolerance(), solver::BicgstabRestart< matrixT >::SetTolerance(), and HeatConduction::x.
TEST() [3/4]
TEST (EllMat , Bicgstab)
Definition at line 87 of file mpi_openmp_matrix_test.cpp.
                       {
  mat::EllMat<double> matA;
  matA.Set(heat_conduction.GetCsr());
  matA.InitMpi(mpi_complex_.GetCommWorld(), matA.col());
  solver::BicgstabMpi<mat::EllMat<double>> solverA(matA);
  mat::CsrMat<double> matB;
  matB.Set(heat_conduction.GetCsr());
  solver::Bicgstab<mat::CsrMat<double>> solverB(matB);
  solverA.SetTolerance(1.0e-9);
  solverB.SetTolerance(1.0e-9);
  for (int i = 0; i < 100; i++) {
    auto resultA = heat_conduction.x;
    auto resultB = heat_conduction.x;
    solverA(heat_conduction.rhs, resultA);
    solverB(heat_conduction.rhs, resultB);
    EXPECT_TRUE(L2Norm(resultA, resultB) < 1.0e-8);
  }
}
References mat::SparseMat< T >::col(), HeatConduction::GetCsr(), heat_conduction, mat::SparseMat< T >::InitMpi(), L2Norm(), mpi_complex_, HeatConduction::rhs, mat::CsrMat< T >::Set(), mat::EllMat< T >::Set(), solver::LinearSolver< matrixT >::SetTolerance(), solver::LinearSolverMpi< MatType >::SetTolerance(), and HeatConduction::x.
TEST() [4/4]
TEST (EllMat , BicgstabRestartMpi)
Definition at line 65 of file mpi_openmp_matrix_test.cpp.
                                 {
  mat::EllMat<double> matA;
  matA.Set(heat_conduction.GetCsr());
  matA.InitMpi(mpi_complex_.GetCommWorld(), matA.col());
  solver::BicgstabRestartMpi<mat::EllMat<double>> solverA(matA);
  mat::CsrMat<double> matB;
  matB.Set(heat_conduction.GetCsr());
  solver::BicgstabRestart<mat::CsrMat<double>> solverB(matB);
  solverA.SetTolerance(1.0e-9);
  solverB.SetTolerance(1.0e-9);
  for (int i = 0; i < 100; i++) {
    auto resultA = heat_conduction.x;
    auto resultB = heat_conduction.x;
    solverA(heat_conduction.rhs, resultA);
    solverB(heat_conduction.rhs, resultB);
    EXPECT_TRUE(L2Norm(resultA, resultB) < 1.0e-8);
  }
}
References mat::SparseMat< T >::col(), HeatConduction::GetCsr(), heat_conduction, mat::SparseMat< T >::InitMpi(), L2Norm(), mpi_complex_, HeatConduction::rhs, mat::CsrMat< T >::Set(), mat::EllMat< T >::Set(), solver::BicgstabRestartMpi< matrixT >::SetTolerance(), solver::BicgstabRestart< matrixT >::SetTolerance(), and HeatConduction::x.
Variable Documentation
heat_conduction
HeatConduction heat_conduction(100) (100)
Referenced by TEST(), TEST(), TEST(), and TEST().
mpi_complex_
mpi::MpiComplex mpi_complex_
Definition at line 16 of file mpi_openmp_matrix_test.cpp.
Referenced by main(), TEST(), TEST(), TEST(), and TEST().