math Namespace Reference
Functions
void init (std::vector< double > &a, const double val)
void init (std::vector< double > &a, const std::vector< double > &b)
void copy (const std::vector< double > &a, std::vector< double > &b)
double InnerProduct (const std::vector< double > &a, const std::vector< double > &b)
double L2Norm (const std::vector< double > &a)
void zero (std::vector< double > &a)
Function Documentation
copy()
void math::copy (const std::vector< double > & a, std::vector< double > & b) [inline]
Definition at line 31 of file math.hpp.
{ init(b, a); }
References init().
Referenced by solver::BicgstabRestartMpi< matrixT >::solve(), and solver::BicgstabRestart< matrixT >::solve().
init() [1/2]
void math::init (std::vector< double > & a, const double val) [inline]
Definition at line 10 of file math.hpp.
                                                             {
      auto A = a.data();
      auto len = a.size();
#pragma omp parallel for simd default(none) firstprivate(A, val, len) \
    schedule(static)
      for (size_t i = 0; i < len; ++i) {
        *(A + i) = val;
      }
    }
Referenced by copy(), and zero().
init() [2/2]
void math::init (std::vector< double > & a, const std::vector< double > & b) [inline]
Definition at line 20 of file math.hpp.
                                                                       {
      size_t len = a.size();
      auto A = a.data();
      auto B = b.data();
#pragma omp parallel for simd default(none) firstprivate(A, len, B) \
    schedule(static)
      for (size_t i = 0; i < len; ++i) {
        *(A + i) = *(B + i);
      }
    }
InnerProduct()
double math::InnerProduct (const std::vector< double > & a, const std::vector< double > & b) [inline]
Definition at line 36 of file math.hpp.
    {
        double r{0.0};
        auto len = a.size();
        auto A = a.data();
        auto B = b.data();
        #pragma omp parallel for simd reduction(+:r) default(none) \
        firstprivate(A, B, len) schedule(static)
        for(size_t i=0; i<len ; ++i)
        { r += *(A+i) * *(B+i); }
        return r;
    }
Referenced by solver::LinearSolver< matrixT >::InnerProduct(), L2Norm(), solver::Bicgstab< MatType >::solve(), and solver::BicgstabRestart< matrixT >::solve().
L2Norm()
double math::L2Norm (const std::vector< double > & a) [inline]
Definition at line 53 of file math.hpp.
    { return sqrt(InnerProduct(a,a)); }
References InnerProduct().
Referenced by solver::Bicgstab< MatType >::solve(), and solver::BicgstabRestart< matrixT >::solve().
zero()
void math::zero (std::vector< double > & a) [inline]
Definition at line 58 of file math.hpp.
{ init(a, 0.0); }
References init().