mpi Namespace Reference
Classes
class MpiComplex
class MpiTool
Functions
int GetRank (MPI_Comm word)
int GetRank ()
int GetSize ()
int GetSize (MPI_Comm word)
void PrintMpiInfo ()
Function Documentation
GetRank() [1/2]
int mpi::GetRank ()
Definition at line 11 of file mpi_getter.hpp.
              {
  int rank;
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  return rank;
}
Referenced by projection_method::CpuOpenMpMpi::CpuOpenMpMpi(), mat::MpiVectorTool::Init(), and mpi::MpiTool::MpiTool().
GetRank() [2/2]
int mpi::GetRank (MPI_Comm word)
Definition at line 5 of file mpi_getter.hpp.
                           {
  int rank;
  MPI_Comm_rank(word, &rank);
  return rank;
}
GetSize() [1/2]
int mpi::GetSize ()
Definition at line 17 of file mpi_getter.hpp.
              {
  int size;
  MPI_Comm_size(MPI_COMM_WORLD, &size);
  return size;
}
Referenced by projection_method::CpuOpenMpMpi::CpuOpenMpMpi(), mat::MpiVectorTool::Init(), mat::MpiVectorTool::Init(), and mpi::MpiTool::MpiTool().
GetSize() [2/2]
int mpi::GetSize (MPI_Comm word)
Definition at line 23 of file mpi_getter.hpp.
                           {
  int size;
  MPI_Comm_size(word, &size);
  return size;
}
PrintMpiInfo()
void mpi::PrintMpiInfo ()
Definition at line 5 of file PrintMpiInfor.hpp.
                    {
  char name[1024];
  int length = 1024, minor;
  MPI_Get_processor_name(name, &length);
  int major;
  MPI_Get_version(&major, &minor);
  // MPI_Request req[10];
  std::cout << "\nMPI Version " << major << "." << minor << std::endl;
  std::cout << "This Project is from " << name << std::endl;
}