tests/validationRe100Cavity/test.cpp File Reference
#include <gtest/gtest.h>
#include "../../cfd_mx/inc/backend/simulation.hpp"
#include "../../cfd_mx/inc/grid/structured_grid.hpp"
#include "../../cfd_mx/inc/grid/uniform_structured_grid.hpp"
#include "../../cfd_mx/inc/io/plot3d/read_qfile.hpp"
#include "../../cfd_mx/inc/run/run_cpu.hpp"
#include "../validation_tool/l2norm_validation.hpp"
Functions
TEST (re100, test1)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 37 of file test.cpp.
                                {
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
TEST()
TEST (re100 , test1)
Definition at line 11 of file test.cpp.
                   {
  Simulation simu;
  UniformStructuredGrid grid(40, 40, 40);
  grid.setLen(1, 1, 1).Init();
  simu.SetReynoldsNumber(100.0)
      .tva.SetDt(0.001)
      .SetWritingDt(1)
      .SetTerminalTime(19);
  
  grid.bc_selector.CavityFlow();
    
  projection_method::CpuOpenMp projection_method(simu, grid);
  projection_method.solve();
  auto validation = get<5>(ReadQfile(grid, "P3D19.q"));
  auto result = get<5>(ReadQfile(grid, "mx_out/P3D19.q"));
  for (int i = 0; i < result.size(); i++) {
    auto l2norm = L2Norm(validation[i], result[i]);
    std::cout << "l2norm: " << l2norm << std::endl;
    EXPECT_TRUE(l2norm < 1.0e-6);
  }
}
References StructuredGrid::bc_selector, BoundaryConditionSelector::CavityFlow(), StructuredGrid::Init(), L2Norm(), ReadQfile(), TimeVarianceAuthority::SetDt(), StructuredGrid::setLen(), Simulation::SetReynoldsNumber(), TimeVarianceAuthority::SetTerminalTime(), TimeVarianceAuthority::SetWritingDt(), and Simulation::tva.